# Generated by Django 5.2.7 on 2025-10-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_rep_legal', models.CharField(max_length=100, verbose_name='Nombre Representante Legal')),
                ('nombre_supervisor_op', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Supervisor Operativo')),
                ('email_supervisor_op', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Supervisor Operativo')),
            ],
            options={
                'verbose_name': 'Arrendatario',
                'verbose_name_plural': 'Arrendatarios',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial_stand', models.CharField(max_length=100, unique=True, verbose_name='Nombre Comercial/Stand')),
                ('total_area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Total (m²)')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre_comercial_stand'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('fecha_inicial_contrato', models.DateField(verbose_name='Fecha Inicial del Contrato')),
                ('fecha_final_inicial', models.DateField(verbose_name='Fecha Final Inicial')),
                ('fecha_final_actualizada', models.DateField(verbose_name='Fecha Final Actualizada')),
                ('prorroga_automatica', models.BooleanField(default=False, verbose_name='Prórroga Automática')),
                ('dias_preaviso_no_renovacion', models.IntegerField(default=60, verbose_name='Días Preaviso No Renovación')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('modalidad_pago', models.CharField(choices=[('Fijo', 'Fijo'), ('Variable Puro', 'Variable Puro'), ('Hibrido (Min Garantizado)', 'Híbrido (Min Garantizado)')], max_length=30, verbose_name='Modalidad de Pago')),
                ('valor_canon_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Canon Fijo')),
                ('canon_minimo_garantizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Canon Mínimo Garantizado')),
                ('porcentaje_ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Ventas (%)')),
                ('reporta_ventas', models.BooleanField(default=False, verbose_name='Reporta Ventas')),
                ('dia_limite_reporte_ventas', models.IntegerField(blank=True, null=True, verbose_name='Día Límite Reporte de Ventas')),
                ('fecha_inicio_periodo_gracia', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Periodo de Gracia')),
                ('fecha_fin_periodo_gracia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Periodo de Gracia')),
                ('clausula_penal_incumplimiento', models.TextField(blank=True, null=True, verbose_name='Cláusula Penal por Incumplimiento')),
                ('interes_mora_pagos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Interés de Mora por Pagos')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.arrendatario', verbose_name='Arrendatario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicial_contrato'],
            },
        ),
        migrations.CreateModel(
            name='OtroSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otrosi', models.DateField(verbose_name='Fecha Otro Sí')),
                ('nueva_fecha_final_actualizada', models.DateField(verbose_name='Nueva Fecha Final Actualizada')),
                ('nuevo_valor_canon', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nuevo Valor Canon')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrosi', to='gestion.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Otro Sí',
                'verbose_name_plural': 'Otros Sí',
                'ordering': ['-fecha_otrosi'],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cumplimiento', 'Cumplimiento'), ('RCE - Responsabilidad Civil', 'RCE - Responsabilidad Civil'), ('Arrendamiento', 'Arrendamiento'), ('Otra', 'Otra')], max_length=30, verbose_name='Tipo de Póliza')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='Número de Póliza')),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Asegurado')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado_aportado', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencida', 'Vencida'), ('No Aportada', 'No Aportada')], default='No Aportada', max_length=20, verbose_name='Estado Aportado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='gestion.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
