# Generated by Django 5.2.7 on 2025-10-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='cobertura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cobertura de la Póliza'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='condiciones',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones de la Póliza'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='garantias',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusulas de Garantías'),
        ),
    ]
