# Generated by Django 5.2.7 on 2025-10-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_poliza_aseguradora_poliza_cobertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='objeto_destinacion',
            field=models.TextField(default='', verbose_name='Objeto y Destinación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('Concesión de Espacio', 'Concesión de Espacio'), ('Arrendamiento Local', 'Arrendamiento Local'), ('Licencia de Uso', 'Licencia de Uso'), ('Otro', 'Otro')], default='Concesión de Espacio', max_length=50, verbose_name='Tipo de Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='nit_concedente',
            field=models.CharField(default='860509249', max_length=20, verbose_name='NIT Concedente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='rep_legal_concedente',
            field=models.CharField(default='MARIA CRISTINA CÉSPEDES BÁEZ', max_length=100, verbose_name='Representante Legal Concedente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='marca_comercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca Comercial'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='supervisor_concedente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor Concedente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='supervisor_concesionario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor Concesionario'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(default='2023-10-17', verbose_name='Fecha de Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='duracion_inicial_meses',
            field=models.IntegerField(default=12, verbose_name='Duración Inicial (Meses)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_periodo_gracia',
            field=models.BooleanField(default=False, verbose_name='Tiene Periodo de Gracia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='condicion_gracia',
            field=models.TextField(blank=True, null=True, verbose_name='Condición de Gracia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cobra_servicios_publicos_aparte',
            field=models.BooleanField(default=False, verbose_name='Cobra Servicios Públicos Aparte'),
        ),
    ]
