# Generated by Django 5.2.7 on 2025-10-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20251023_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='exige_poliza_cumplimiento',
            field=models.BooleanField(default=False, verbose_name='Exige Póliza de Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_asegurado_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Asegurado Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vigencia_requerida_cumplimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigencia Requerida Cumplimiento (meses)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='exige_poliza_rce',
            field=models.BooleanField(default=False, verbose_name='Exige Póliza RCE'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_asegurado_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Asegurado RCE'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vigencia_requerida_rce',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigencia Requerida RCE (meses)'),
        ),
    ]
