# Generated by Django 5.2.7 on 2025-10-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20251023_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('nit_empresa', models.CharField(max_length=20, verbose_name='NIT de la Empresa')),
                ('representante_legal', models.CharField(max_length=100, verbose_name='Representante Legal')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='clausula_penal_incumplimiento',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='modalidad_pago',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Variable Puro', 'Variable Puro'), ('Hibrido (Min Garantizado)', 'Híbrido (Min Garantizado)')], max_length=30, null=True, verbose_name='Modalidad de Pago'),
        ),
    ]
