# Generated by Django 5.2.7 on 2025-10-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_configuracionempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='clausula_penal_incumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cláusula Penal por Incumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='multa_mora_no_restitucion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Multa por Mora en No Restitución'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='penalidad_terminacion_anticipada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Penalidad por Terminación Anticipada'),
        ),
    ]
