# Generated by Django 5.2.7 on 2025-10-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_contrato_clausula_penal_incumplimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['-fecha_vencimiento'], 'verbose_name': 'Póliza (Deprecated)', 'verbose_name_plural': 'Pólizas (Deprecated)'},
        ),
        migrations.CreateModel(
            name='RequerimientoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cumplimiento', 'Cumplimiento'), ('RCE - Responsabilidad Civil', 'RCE - Responsabilidad Civil'), ('Arrendamiento', 'Arrendamiento'), ('Otra', 'Otra')], max_length=30, verbose_name='Tipo de Póliza Requerida')),
                ('valor_asegurado_requerido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Asegurado Requerido')),
                ('vigencia_requerida_meses', models.IntegerField(verbose_name='Vigencia Requerida (meses)')),
                ('condiciones_especiales', models.TextField(blank=True, null=True, verbose_name='Condiciones Especiales')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos_poliza', to='gestion.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Requerimiento de Póliza',
                'verbose_name_plural': 'Requerimientos de Póliza',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='PolizaAportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cumplimiento', 'Cumplimiento'), ('RCE - Responsabilidad Civil', 'RCE - Responsabilidad Civil'), ('Arrendamiento', 'Arrendamiento'), ('Otra', 'Otra')], max_length=30, verbose_name='Tipo de Póliza')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='Número de Póliza')),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Asegurado')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado_aportado', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencida', 'Vencida'), ('No Aportada', 'No Aportada')], default='No Aportada', max_length=20, verbose_name='Estado Aportado')),
                ('aseguradora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aseguradora')),
                ('cobertura', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cobertura de la Póliza')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones de la Póliza')),
                ('garantias', models.TextField(blank=True, null=True, verbose_name='Cláusulas de Garantías')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas_aportadas', to='gestion.contrato', verbose_name='Contrato')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas_aportadas', to='gestion.requerimientopoliza', verbose_name='Requerimiento')),
            ],
            options={
                'verbose_name': 'Póliza Aportada',
                'verbose_name_plural': 'Pólizas Aportadas',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
