# Generated by Django 5.2.7 on 2025-10-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_poliza_options_requerimientopoliza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_asegurado_cumplimiento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_asegurado_rce',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='vigencia_requerida_cumplimiento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='vigencia_requerida_rce',
        ),
        migrations.AddField(
            model_name='contrato',
            name='condiciones_cumplimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones Específicas Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='condiciones_otra_1',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones Específicas Otra Póliza'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='condiciones_rce',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones Específicas RCE'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='exige_poliza_otra_1',
            field=models.BooleanField(default=False, verbose_name='¿Exige Otra Póliza?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nombre_poliza_otra_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Otra Póliza'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_requerido_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Asegurado Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_requerido_otra_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Asegurado Otra Póliza'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_requerido_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Asegurado RCE'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='exige_poliza_cumplimiento',
            field=models.BooleanField(default=False, verbose_name='¿Exige Póliza de Cumplimiento?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='exige_poliza_rce',
            field=models.BooleanField(default=False, verbose_name='¿Exige Póliza RCE?'),
        ),
    ]
