# Generated by Django 5.2.7 on 2025-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_contrato_valor_asegurado_cumplimiento_and_more'),
    ]

    operations = [
        # Renombrar campos existentes
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_requerido_rce',
            new_name='valor_asegurado_rce',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_requerido_cumplimiento',
            new_name='valor_asegurado_cumplimiento',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_requerido_otra_1',
            new_name='valor_asegurado_otra_1',
        ),
        
        # Eliminar campos de condiciones
        migrations.RemoveField(
            model_name='contrato',
            name='condiciones_rce',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='condiciones_cumplimiento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='condiciones_otra_1',
        ),
        
        # Añadir campos de fechas de vigencia
        migrations.AddField(
            model_name='contrato',
            name='fecha_inicio_vigencia_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_fin_vigencia_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_inicio_vigencia_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_fin_vigencia_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_inicio_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia Otra Póliza'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_fin_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia Otra Póliza'),
        ),
    ]
