# Generated by Django 5.2.7 on 2025-10-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20251024_0010'),
    ]

    operations = [
        # Añadir campos de meses de vigencia
        migrations.AddField(
            model_name='contrato',
            name='meses_vigencia_rce',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses de Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='meses_vigencia_cumplimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses de Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='meses_vigencia_otra_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses de Vigencia Otra Póliza'),
        ),
    ]
