# Generated by Django 5.2.7 on 2025-10-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20251024_0017'),
    ]

    operations = [
        # Añadir campos para Todo Riesgo para Equipos
        migrations.AddField(
            model_name='contrato',
            name='exige_poliza_todo_riesgo',
            field=models.BooleanField(default=False, verbose_name='¿Exige Póliza Todo Riesgo para Equipos?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_asegurado_todo_riesgo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Asegurado Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='meses_vigencia_todo_riesgo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses de Vigencia Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_inicio_vigencia_todo_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_fin_vigencia_todo_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia Todo Riesgo'),
        ),
    ]
