# Generated by Django 5.2.7 on 2025-10-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20251024_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='exige_poliza_otra_1',
            field=models.BooleanField(default=False, verbose_name='¿Exige Otras Pólizas?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia Otras Pólizas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_final_actualizada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Final Actualizada'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia Otras Pólizas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='meses_vigencia_otra_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses de Vigencia Otras Pólizas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_poliza_otra_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Otras Pólizas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_asegurado_otra_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Asegurado Otras Pólizas'),
        ),
    ]
