# Generated by Django 5.2.7 on 2025-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_contrato_exige_poliza_otra_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='mes_aumento_ipc',
            field=models.CharField(blank=True, choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], max_length=20, null=True, verbose_name='Mes de Aumento IPC'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='periodicidad_ipc',
            field=models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('MES_ESPECIFICO', 'Mes Específico')], max_length=20, null=True, verbose_name='Periodicidad IPC'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='puntos_adicionales_ipc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntos Adicionales IPC'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_condicion_ipc',
            field=models.CharField(blank=True, choices=[('IPC', 'IPC'), ('SALARIO_MINIMO', 'Porcentaje Salario Mínimo')], max_length=20, null=True, verbose_name='Tipo de Condición IPC'),
        ),
    ]
