# Generated by Django 5.2.7 on 2025-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_contrato_mes_aumento_ipc_contrato_periodicidad_ipc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_inicio_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Vigencia'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cobertura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Características de la Póliza'),
        ),
        migrations.AlterField(
            model_name='polizaaportada',
            name='cobertura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Características de la Póliza'),
        ),
    ]
