# Generated by Django 5.2.7 on 2025-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_poliza_fecha_inicio_vigencia_alter_poliza_cobertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='meses_cobertura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses de Cobertura'),
        ),
    ]
