# Generated by Django 5.2.7 on 2025-10-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_poliza_meses_cobertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='meses_cobertura',
        ),
    ]
