# Generated by Django 5.2.7 on 2025-10-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_remove_poliza_meses_cobertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado_aportado',
            field=models.CharField(choices=[('Aporte inicial', 'Aporte inicial'), ('Actualización', 'Actualización'), ('Prórroga', 'Prórroga')], default='Aporte inicial', max_length=20, verbose_name='Estado Aportado'),
        ),
        migrations.AlterField(
            model_name='polizaaportada',
            name='estado_aportado',
            field=models.CharField(choices=[('Aporte inicial', 'Aporte inicial'), ('Actualización', 'Actualización'), ('Prórroga', 'Prórroga')], default='Aporte inicial', max_length=20, verbose_name='Estado Aportado'),
        ),
    ]
