# Generated by Django 5.2.7 on 2025-10-26 02:22

from django.db import migrations


def migrate_estado_aportado_data(apps, schema_editor):
    """
    Migración de datos para actualizar el campo estado_aportado
    de los valores antiguos a los nuevos.
    
    Mapeo:
    - 'Vigente' -> 'Aporte inicial'
    - 'Vencida' -> 'Aporte inicial'
    - 'No Aportada' -> 'Aporte inicial'
    """
    Poliza = apps.get_model('gestion', 'Poliza')
    PolizaAportada = apps.get_model('gestion', 'PolizaAportada')
    
    # Mapeo de valores antiguos a nuevos
    mapeo = {
        'Vigente': 'Aporte inicial',
        'Vencida': 'Aporte inicial',
        'No Aportada': 'Aporte inicial',
    }
    
    # Migrar Poliza
    for poliza in Poliza.objects.all():
        if poliza.estado_aportado in mapeo:
            poliza.estado_aportado = mapeo[poliza.estado_aportado]
            poliza.save()
    
    # Migrar PolizaAportada
    for poliza in PolizaAportada.objects.all():
        if poliza.estado_aportado in mapeo:
            poliza.estado_aportado = mapeo[poliza.estado_aportado]
            poliza.save()


def reverse_migrate_estado_aportado_data(apps, schema_editor):
    """
    Reversión de la migración de datos.
    
    Mapeo inverso:
    - 'Aporte inicial' -> 'Vigente'
    - 'Actualización' -> 'Vigente'
    - 'Prórroga' -> 'Vigente'
    """
    Poliza = apps.get_model('gestion', 'Poliza')
    PolizaAportada = apps.get_model('gestion', 'PolizaAportada')
    
    # Mapeo inverso simplificado (todos a 'Vigente')
    mapeo_inverso = {
        'Aporte inicial': 'Vigente',
        'Actualización': 'Vigente',
        'Prórroga': 'Vigente',
    }
    
    # Revertir Poliza
    for poliza in Poliza.objects.all():
        if poliza.estado_aportado in mapeo_inverso:
            poliza.estado_aportado = mapeo_inverso[poliza.estado_aportado]
            poliza.save()
    
    # Revertir PolizaAportada
    for poliza in PolizaAportada.objects.all():
        if poliza.estado_aportado in mapeo_inverso:
            poliza.estado_aportado = mapeo_inverso[poliza.estado_aportado]
            poliza.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_poliza_estado_aportado_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_estado_aportado_data, reverse_migrate_estado_aportado_data),
    ]
