# Generated by Django 5.2.7 on 2025-10-27 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_poliza_estado_aportado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrosi',
            options={'ordering': ['-effective_from', '-version'], 'verbose_name': 'Otro Sí', 'verbose_name_plural': 'Otros Sí'},
        ),
        migrations.AddField(
            model_name='otrosi',
            name='aprobado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprobado Por'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='clausulas_modificadas',
            field=models.TextField(blank=True, help_text='Detalle de cláusulas específicas modificadas', null=True, verbose_name='Cláusulas Modificadas'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='effective_from',
            field=models.DateField(default='2025-01-01', help_text='Fecha desde la cual aplican los cambios', verbose_name='Vigencia Desde'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual aplican los cambios (opcional)', null=True, verbose_name='Vigencia Hasta'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='justificacion_legal',
            field=models.TextField(blank=True, null=True, verbose_name='Justificación Legal/Contractual'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última Modificación Por'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nueva_modalidad_pago',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nueva Modalidad de Pago'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nueva_periodicidad_ipc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nueva Periodicidad IPC'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_canon_minimo_garantizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Nuevo Canon Mínimo'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_mes_aumento_ipc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nuevo Mes Aumento IPC'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_plazo_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuevo Plazo (Meses)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_porcentaje_ventas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nuevo % Ventas'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_tipo_condicion_ipc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nuevo Tipo IPC'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevos_puntos_adicionales_ipc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nuevos Puntos IPC'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='numero_otrosi',
            field=models.CharField(default='OS-TEMP', max_length=50, verbose_name='Número de Otro Sí'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='tipo',
            field=models.CharField(choices=[('AMENDMENT', 'Modificación General'), ('RENEWAL', 'Renovación'), ('IPC_UPDATE', 'Actualización IPC'), ('CANON_CHANGE', 'Cambio de Canon'), ('PLAZO_EXTENSION', 'Extensión de Plazo'), ('POLIZAS_UPDATE', 'Actualización de Pólizas'), ('OTRO', 'Otro')], default='AMENDMENT', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de los cambios'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='fecha_otrosi',
            field=models.DateField(verbose_name='Fecha del Otro Sí'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nueva_fecha_final_actualizada',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Final'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nuevo_valor_canon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Nuevo Valor Canon'),
        ),
        migrations.AlterUniqueTogether(
            name='otrosi',
            unique_together={('contrato', 'numero_otrosi')},
        ),
    ]
