# Generated by Django 5.2.7 on 2025-10-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_mejorar_modelo_otrosi'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='modifica_polizas',
            field=models.BooleanField(default=False, help_text='Indica si este Otro Sí actualiza pólizas del contrato', verbose_name='¿Modifica Pólizas?'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='notas_polizas',
            field=models.TextField(blank=True, help_text='Descripción de las modificaciones en pólizas', null=True, verbose_name='Notas sobre Pólizas'),
        ),
    ]
