# Generated by Django 5.2.7 on 2025-10-28 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_agregar_polizas_a_otrosi'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='otrosi',
            field=models.ForeignKey(blank=True, help_text='Si pertenece a un Otro Sí específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_modificadas', to='gestion.otrosi', verbose_name='Otro Sí'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nuevo_canon_minimo_garantizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Canon Mínimo'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nuevo_valor_canon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Valor Canon'),
        ),
    ]
