# Generated by Django 5.2.7 on 2025-10-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_agregar_otrosi_a_poliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrosi',
            name='nueva_periodicidad_ipc',
            field=models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('MES_ESPECIFICO', 'Mes Específico')], max_length=20, null=True, verbose_name='Nueva Periodicidad IPC'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nuevo_mes_aumento_ipc',
            field=models.CharField(blank=True, choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], max_length=20, null=True, verbose_name='Nuevo Mes Aumento IPC'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nuevo_tipo_condicion_ipc',
            field=models.CharField(blank=True, choices=[('IPC', 'IPC'), ('SALARIO_MINIMO', 'Porcentaje Salario Mínimo')], max_length=20, null=True, verbose_name='Nuevo Tipo IPC'),
        ),
    ]
