# Generated by Django 5.0.14 on 2025-10-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_alter_otrosi_nueva_periodicidad_ipc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='ubicacion',
            field=models.CharField(default='No especificada', help_text='Ejemplo: Primer Piso, Sector A, Corredor Norte', max_length=200, verbose_name='Ubicación'),
        ),
    ]
