# Generated by Django 5.0.14 on 2025-11-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_poliza_rce_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('AIRE ACONDICIONADO', 'AIRE ACONDICIONADO'), ('ANTENAS', 'ANTENAS'), ('BODEGAS', 'BODEGAS'), ('ESTACIONAMIENTO', 'ESTACIONAMIENTO'), ('PUBLICIDAD', 'PUBLICIDAD'), ('STAND PRIMER PISO', 'STAND PRIMER PISO'), ('STAND SEGUNDO PISO', 'STAND SEGUNDO PISO'), ('STAND TERCER PISO', 'STAND TERCER PISO'), ('ARRIENDO PLAZOLETA', 'ARRIENDO PLAZOLETA'), ('STAND SÓTANO', 'STAND SÓTANO')], max_length=50, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_otros_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cuota de Administración Asegurada (Arrendamiento)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_otros_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cuota de Administración Asegurada (Cumplimiento)'),
        ),
        migrations.AlterField(
            model_name='seguimientopoliza',
            name='poliza_tipo',
            field=models.CharField(blank=True, choices=[('Cumplimiento', 'Cumplimiento'), ('Poliza de Arrendamiento', 'Póliza de Arrendamiento'), ('RCE - Responsabilidad Civil', 'RCE - Responsabilidad Civil'), ('Arrendamiento', 'Arrendamiento'), ('Otra', 'Otra')], max_length=30, null=True, verbose_name='Tipo de Póliza'),
        ),
    ]
