# Generated by Django 5.0.14 on 2025-11-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_poliza_detalles'),
        ('gestion', '0031_contrato_terminacion_anticipada'),
    ]

    operations = [
    ]
