# Generated by Django 5.0.14 on 2025-11-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_agregar_campos_polizas_otrosi'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_fin_vigencia_arrendamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Póliza de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_fin_vigencia_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_fin_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_fin_vigencia_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_fin_vigencia_todo_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_inicio_vigencia_arrendamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Póliza de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_inicio_vigencia_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_inicio_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_inicio_vigencia_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_fecha_inicio_vigencia_todo_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Todo Riesgo'),
        ),
    ]
