# Generated by Django 5.0.14 on 2025-11-14 22:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_actualizar_numeros_otrosi'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Mes del informe', verbose_name='Mes')),
                ('año', models.IntegerField(help_text='Año del informe', verbose_name='Año')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha en que se entregó el informe', null=True, verbose_name='Fecha de Entrega')),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite para entregar el informe', null=True, verbose_name='Fecha Límite')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el informe', null=True, verbose_name='Observaciones')),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Registrado por')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_ventas', to='gestion.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Informe de Ventas',
                'verbose_name_plural': 'Informes de Ventas',
                'ordering': ['-año', '-mes', 'contrato'],
                'indexes': [models.Index(fields=['contrato', 'año', 'mes'], name='gestion_inf_contrat_585426_idx'), models.Index(fields=['estado'], name='gestion_inf_estado_ddcc41_idx')],
                'unique_together': {('contrato', 'mes', 'año')},
            },
        ),
    ]
