# Generated by Django 5.0.14 on 2025-11-14 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_informeventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoFacturacionVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Mes al que corresponden las ventas', verbose_name='Mes')),
                ('año', models.IntegerField(help_text='Año al que corresponden las ventas', verbose_name='Año')),
                ('ventas_totales', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ventas Totales')),
                ('devoluciones', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Devoluciones')),
                ('base_neta', models.DecimalField(decimal_places=2, help_text='Ventas Totales - Devoluciones', max_digits=20, verbose_name='Base Neta')),
                ('modalidad_contrato', models.CharField(choices=[('VARIABLE_PURO', 'Variable Puro'), ('HIBRIDO_MIN_GARANTIZADO', 'Híbrido (Min Garantizado)')], max_length=30, verbose_name='Modalidad del Contrato')),
                ('porcentaje_ventas_vigente', models.DecimalField(decimal_places=2, help_text='Porcentaje vigente al momento del cálculo', max_digits=5, verbose_name='Porcentaje de Ventas Vigente (%)')),
                ('canon_minimo_garantizado_vigente', models.DecimalField(blank=True, decimal_places=2, help_text='Mínimo garantizado vigente (solo para Híbrido)', max_digits=20, null=True, verbose_name='Canon Mínimo Garantizado Vigente')),
                ('canon_fijo_vigente', models.DecimalField(blank=True, decimal_places=2, help_text='Canon fijo vigente (si aplica)', max_digits=20, null=True, verbose_name='Canon Fijo Vigente')),
                ('valor_calculado_porcentaje', models.DecimalField(decimal_places=2, help_text='Base neta × Porcentaje', max_digits=20, verbose_name='Valor Calculado (Base × %)')),
                ('valor_a_facturar_variable', models.DecimalField(decimal_places=2, help_text='Valor variable a facturar (después de aplicar mínimo garantizado si aplica)', max_digits=20, verbose_name='Valor a Facturar Variable')),
                ('excedente_sobre_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Excedente sobre el mínimo garantizado (solo para Híbrido)', max_digits=20, null=True, verbose_name='Excedente sobre Mínimo')),
                ('aplica_variable', models.BooleanField(default=False, help_text='Indica si se aplica facturación variable o solo el mínimo garantizado', verbose_name='¿Aplica Variable?')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el cálculo', null=True, verbose_name='Observaciones')),
                ('calculado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calculado por')),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Cálculo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_facturacion', to='gestion.contrato', verbose_name='Contrato')),
                ('informe_ventas', models.ForeignKey(blank=True, help_text='Informe de ventas asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_facturacion', to='gestion.informeventas', verbose_name='Informe de Ventas')),
                ('otrosi_referencia', models.ForeignKey(blank=True, help_text='Otro Sí vigente usado para el cálculo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_facturacion', to='gestion.otrosi', verbose_name='Otro Sí de Referencia')),
            ],
            options={
                'verbose_name': 'Cálculo de Facturación por Ventas',
                'verbose_name_plural': 'Cálculos de Facturación por Ventas',
                'ordering': ['-fecha_calculo', '-año', '-mes'],
                'indexes': [models.Index(fields=['contrato', 'año', 'mes'], name='gestion_cal_contrat_7d8187_idx'), models.Index(fields=['fecha_calculo'], name='gestion_cal_fecha_c_1831dc_idx')],
            },
        ),
    ]
