# Generated by Django 5.0.14 on 2025-11-16 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_add_cobro_administracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(help_text='Año del IPC certificado por el DANE', unique=True, verbose_name='Año')),
                ('valor_ipc', models.DecimalField(decimal_places=2, help_text='Valor del IPC en porcentaje (ej: 5.2 para 5.2%)', max_digits=6, verbose_name='Valor IPC (%)')),
                ('fecha_certificacion', models.DateField(blank=True, help_text='Fecha en que el DANE certificó este valor', null=True, verbose_name='Fecha de Certificación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este valor de IPC', null=True, verbose_name='Observaciones')),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'IPC Histórico',
                'verbose_name_plural': 'IPC Histórico',
                'ordering': ['-año'],
                'indexes': [models.Index(fields=['año'], name='gestion_ipc_año_dbe4ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalculoIPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_aplicacion', models.IntegerField(help_text='Año para el cual se aplica el ajuste por IPC', verbose_name='Año de Aplicación')),
                ('canon_anterior', models.DecimalField(decimal_places=2, help_text='Canon base sobre el cual se calcula el ajuste', max_digits=20, verbose_name='Canon Anterior')),
                ('canon_anterior_manual', models.BooleanField(default=False, help_text='Indica si el canon anterior fue ingresado manualmente', verbose_name='Canon Anterior Manual')),
                ('fuente_canon_anterior', models.CharField(blank=True, help_text='Indica de dónde proviene el canon anterior (Otro Sí, cálculo previo, manual)', max_length=100, null=True, verbose_name='Fuente del Canon Anterior')),
                ('puntos_adicionales', models.DecimalField(decimal_places=2, default=0, help_text='Puntos adicionales pactados en el contrato', max_digits=5, verbose_name='Puntos Adicionales IPC')),
                ('porcentaje_total_aplicar', models.DecimalField(decimal_places=2, help_text='IPC + Puntos Adicionales', max_digits=6, verbose_name='Porcentaje Total a Aplicar (%)')),
                ('valor_incremento', models.DecimalField(decimal_places=2, help_text='Valor en pesos del incremento', max_digits=20, verbose_name='Valor del Incremento')),
                ('nuevo_canon', models.DecimalField(decimal_places=2, help_text='Canon Anterior * (1 + (IPC + Puntos Adicionales)/100)', max_digits=20, verbose_name='Nuevo Canon')),
                ('periodicidad_contrato', models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('MES_ESPECIFICO', 'Mes Específico')], help_text='Periodicidad configurada en el contrato', max_length=20, null=True, verbose_name='Periodicidad del Contrato')),
                ('mes_aumento_contrato', models.CharField(blank=True, choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], help_text='Mes configurado en el contrato para el aumento', max_length=20, null=True, verbose_name='Mes de Aumento del Contrato')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este cálculo', null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('calculado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calculado Por')),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Cálculo')),
                ('aplicado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Aplicado Por')),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aplicación')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_ipc', to='gestion.contrato', verbose_name='Contrato')),
                ('ipc_historico', models.ForeignKey(help_text='Valor del IPC certificado por el DANE para este año', on_delete=django.db.models.deletion.PROTECT, related_name='calculos_ipc', to='gestion.ipchistorico', verbose_name='IPC Histórico')),
            ],
            options={
                'verbose_name': 'Cálculo de IPC',
                'verbose_name_plural': 'Cálculos de IPC',
                'ordering': ['-año_aplicacion', '-fecha_calculo'],
                'indexes': [models.Index(fields=['contrato', 'año_aplicacion'], name='gestion_cal_contrat_8c8c9a_idx'), models.Index(fields=['estado'], name='gestion_cal_estado_683960_idx'), models.Index(fields=['fecha_calculo'], name='gestion_cal_fecha_c_39e183_idx')],
                'unique_together': {('contrato', 'año_aplicacion')},
            },
        ),
    ]
