# Generated by Django 5.0.14 on 2025-11-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_ipchistorico_calculoipc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicidadIPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la periodicidad', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la periodicidad', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la periodicidad', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta periodicidad está disponible para usar', verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Periodicidad IPC',
                'verbose_name_plural': 'Periodicidades IPC',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='gestion_per_activo_117792_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoCondicionIPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del tipo de condición', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de condición', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de condición', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo está disponible para usar', verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Condición IPC',
                'verbose_name_plural': 'Tipos de Condición IPC',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='gestion_tip_activo_f59cb4_idx')],
            },
        ),
    ]
