# Generated by Django 5.0.14 on 2025-11-17 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_periodicidadipc_tipocondicionipc'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el contrato', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el contrato', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del contrato', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del contrato', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='local',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='local',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='local',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='local',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='local',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='local',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el Otro Sí', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del Otro Sí', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='polizaaportada',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='polizaaportada',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='polizaaportada',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='polizaaportada',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='polizaaportada',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='polizaaportada',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='requerimientopoliza',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='requerimientopoliza',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='requerimientopoliza',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='requerimientopoliza',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='requerimientopoliza',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='requerimientopoliza',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
    ]
