# Generated by Django 5.0.14 on 2025-11-18 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_agregar_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='Clave de licencia de Firebase (ej: SGC-F9MY-5Q53-E6NA-GWXC)', max_length=50, unique=True, verbose_name='Clave de Licencia')),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente asociado a esta licencia', max_length=200, null=True, verbose_name='Nombre del Cliente')),
                ('customer_email', models.EmailField(blank=True, help_text='Email del cliente asociado a esta licencia', max_length=254, null=True, verbose_name='Email del Cliente')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Fecha de expiración de la licencia', null=True, verbose_name='Fecha de Expiración')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la licencia está activa localmente', verbose_name='Activa')),
                ('last_verification', models.DateTimeField(blank=True, help_text='Última vez que se verificó la licencia con Firebase', null=True, verbose_name='Última Verificación')),
                ('verification_status', models.CharField(choices=[('valid', 'Válida'), ('expired', 'Expirada'), ('invalid', 'Inválida'), ('pending', 'Pendiente')], default='pending', help_text='Estado actual de la verificación', max_length=20, verbose_name='Estado de Verificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado a esta licencia', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_license', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Licencia de Cliente',
                'verbose_name_plural': 'Licencias de Clientes',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['license_key'], name='gestion_cli_license_1ec059_idx'), models.Index(fields=['usuario'], name='gestion_cli_usuario_ec3f1b_idx'), models.Index(fields=['is_active', 'verification_status'], name='gestion_cli_is_acti_7d4a42_idx')],
            },
        ),
    ]
