# Generated by Django 5.0.14 on 2025-11-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_clientelicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientelicense',
            name='verification_status',
            field=models.CharField(choices=[('valid', 'Válida'), ('expired', 'Expirada'), ('invalid', 'Inválida'), ('revoked', 'Revocada'), ('pending', 'Pendiente')], default='pending', help_text='Estado actual de la verificación', max_length=20, verbose_name='Estado de Verificación'),
        ),
    ]
