# Generated by Django 5.0.14 on 2025-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0044_alter_clientelicense_verification_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientelicense',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Licencia de Organización', 'verbose_name_plural': 'Licencias de Organización'},
        ),
        migrations.RemoveIndex(
            model_name='clientelicense',
            name='gestion_cli_usuario_ec3f1b_idx',
        ),
        migrations.RemoveField(
            model_name='clientelicense',
            name='usuario',
        ),
        migrations.AddField(
            model_name='clientelicense',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Indica si esta es la licencia principal activa de la organización. Solo debe haber una licencia principal.', verbose_name='Licencia Principal'),
        ),
        migrations.AlterField(
            model_name='clientelicense',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Email de contacto de la organización', max_length=254, null=True, verbose_name='Email del Cliente'),
        ),
        migrations.AlterField(
            model_name='clientelicense',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Nombre de la organización asociada a esta licencia', max_length=200, null=True, verbose_name='Nombre del Cliente/Organización'),
        ),
        migrations.AlterField(
            model_name='clientelicense',
            name='license_key',
            field=models.CharField(help_text='Clave de licencia de Firebase (compartida por todos los usuarios de la organización)', max_length=50, unique=True, verbose_name='Clave de Licencia'),
        ),
        migrations.AddIndex(
            model_name='clientelicense',
            index=models.Index(fields=['is_primary', 'is_active'], name='gestion_cli_is_prim_284be9_idx'),
        ),
    ]
