# Generated by Django 5.0.14 on 2025-11-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0045_alter_clientelicense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculoipc',
            options={'ordering': ['-año_aplicacion', '-mes_aplicacion', '-fecha_calculo'], 'verbose_name': 'Cálculo de IPC', 'verbose_name_plural': 'Cálculos de IPC'},
        ),
        migrations.RemoveIndex(
            model_name='calculoipc',
            name='gestion_cal_contrat_8c8c9a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calculoipc',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calculoipc',
            name='mes_aplicacion',
            field=models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', help_text='Mes para el cual se aplica el ajuste por IPC', max_length=20, verbose_name='Mes de Aplicación'),
        ),
        migrations.AlterUniqueTogether(
            name='calculoipc',
            unique_together={('contrato', 'año_aplicacion', 'mes_aplicacion')},
        ),
        migrations.AddIndex(
            model_name='calculoipc',
            index=models.Index(fields=['contrato', 'año_aplicacion', 'mes_aplicacion'], name='gestion_cal_contrat_123828_idx'),
        ),
    ]
