# Generated by Django 5.0.14 on 2025-11-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0046_alter_calculoipc_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientopoliza',
            name='poliza_aportada',
        ),
        migrations.DeleteModel(
            name='PolizaAportada',
        ),
    ]
