# Generated by Django 5.0.14 on 2025-11-25 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0047_eliminar_poliza_aportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_ultima_renovacion_automatica',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última renovación automática aprobada', null=True, verbose_name='Fecha Última Renovación Automática'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='total_renovaciones_automaticas',
            field=models.IntegerField(default=0, help_text='Número total de renovaciones automáticas realizadas', verbose_name='Total Renovaciones Automáticas'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ultima_renovacion_automatica_por',
            field=models.CharField(blank=True, help_text='Usuario que aprobó la última renovación automática', max_length=150, null=True, verbose_name='Última Renovación Automática Por'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='effective_from',
            field=models.DateField(default=datetime.date.today, help_text='Fecha desde la cual aplican los cambios', verbose_name='Vigencia Desde'),
        ),
    ]
