# Generated by Django 5.0.14 on 2025-11-25 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0048_agregar_campos_renovacion_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenovacionAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renovacion', models.DateField(help_text='Fecha en que se autorizó la renovación', verbose_name='Fecha de Renovación')),
                ('fecha_inicio_nueva_vigencia', models.DateField(help_text='Fecha desde la cual inicia la nueva vigencia', verbose_name='Fecha Inicio Nueva Vigencia')),
                ('fecha_fin_nueva_vigencia', models.DateField(help_text='Fecha hasta la cual se extiende el contrato', verbose_name='Fecha Fin Nueva Vigencia')),
                ('meses_renovacion', models.IntegerField(help_text='Número de meses por los cuales se renovó el contrato', verbose_name='Meses de Renovación')),
                ('usar_duracion_inicial', models.BooleanField(default=True, help_text='Indica si se usó la duración inicial del contrato para la renovación', verbose_name='Usó Duración Inicial')),
                ('fecha_final_anterior', models.DateField(help_text='Fecha final del contrato antes de la renovación', verbose_name='Fecha Final Anterior')),
                ('autorizado_por', models.CharField(help_text='Usuario que autorizó la renovación automática', max_length=150, verbose_name='Autorizado Por')),
                ('fecha_autorizacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se autorizó la renovación', verbose_name='Fecha de Autorización')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la renovación', null=True, verbose_name='Observaciones')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones_automaticas', to='gestion.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Renovación Automática',
                'verbose_name_plural': 'Renovaciones Automáticas',
                'ordering': ['-fecha_autorizacion'],
                'indexes': [models.Index(fields=['contrato', '-fecha_autorizacion'], name='gestion_ren_contrat_306f72_idx')],
            },
        ),
    ]
