# Generated by Django 5.0.14 on 2025-11-25 04:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0049_crear_modelo_renovacion_automatica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovacionautomatica',
            options={'ordering': ['-fecha_aprobacion', '-effective_from', '-version'], 'verbose_name': 'Renovación Automática', 'verbose_name_plural': 'Renovaciones Automáticas'},
        ),
        migrations.RemoveIndex(
            model_name='renovacionautomatica',
            name='gestion_ren_contrat_306f72_idx',
        ),
        migrations.RemoveField(
            model_name='renovacionautomatica',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='renovacionautomatica',
            name='fecha_autorizacion',
        ),
        migrations.RemoveField(
            model_name='renovacionautomatica',
            name='fecha_fin_nueva_vigencia',
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='anulado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anulado Por'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='aprobado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprobado Por'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la renovación automática', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='effective_from',
            field=models.DateField(default=datetime.date.today, help_text='Fecha desde la cual aplican los cambios', verbose_name='Vigencia Desde'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual aplican los cambios (opcional)', null=True, verbose_name='Vigencia Hasta'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='modifica_polizas',
            field=models.BooleanField(default=False, help_text='Indica si esta renovación actualiza las condiciones de pólizas del contrato', verbose_name='¿Modifica Pólizas?'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última Modificación Por'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nueva_fecha_final_actualizada',
            field=models.DateField(blank=True, help_text='Nueva fecha final del contrato después de la renovación', null=True, verbose_name='Nueva Fecha Final'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_exige_poliza_arrendamiento',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Exige Póliza de Arrendamiento?'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_exige_poliza_cumplimiento',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Exige Póliza de Cumplimiento?'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_exige_poliza_otra_1',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Exige Otras Pólizas?'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_exige_poliza_rce',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Exige Póliza RCE?'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_exige_poliza_todo_riesgo',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Exige Póliza Todo Riesgo para Equipos?'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_fin_vigencia_arrendamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Póliza de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_fin_vigencia_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_fin_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_fin_vigencia_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_fin_vigencia_todo_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Fin Vigencia Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_inicio_vigencia_arrendamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Póliza de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_inicio_vigencia_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_inicio_vigencia_otra_1',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_inicio_vigencia_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_fecha_inicio_vigencia_todo_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Inicio Vigencia Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_meses_vigencia_arrendamiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuevos Meses de Vigencia Póliza de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_meses_vigencia_cumplimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuevos Meses de Vigencia Cumplimiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_meses_vigencia_otra_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuevos Meses de Vigencia Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_meses_vigencia_rce',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuevos Meses de Vigencia RCE'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_meses_vigencia_todo_riesgo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuevos Meses de Vigencia Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_nombre_poliza_otra_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuevo Nombre Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_asegurado_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Valor Asegurado Póliza de Arrendamiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_asegurado_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Valor Asegurado Cumplimiento'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_asegurado_otra_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Valor Asegurado Otras Pólizas'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_asegurado_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Valor Asegurado RCE'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_asegurado_todo_riesgo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Valor Asegurado Todo Riesgo'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_contratistas_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Contratistas y Subcontratistas Asegurados'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_dano_moral_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daño Moral Asegurado'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_gastos_medicos_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Gastos Médicos de Terceros Asegurados'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_iva_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo IVA Asegurado (Arrendamiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_iva_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo IVA Asegurado (Cumplimiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_lucro_cesante_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Lucro Cesante Asegurado'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_otros_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Cuota de Administración Asegurada (Arrendamiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_otros_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Cuota de Administración Asegurada (Cumplimiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_patronal_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Patronal Asegurado'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_perjuicios_extrapatrimoniales_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Perjuicios Extrapatrimoniales Asegurados'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_propietario_locatario_ocupante_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo PLO (Propietario, Locatario y Ocupante) Asegurado'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_remuneraciones_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Remuneraciones Mensuales Aseguradas (Arrendamiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_remuneraciones_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Remuneraciones Mensuales Aseguradas (Cumplimiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_servicios_publicos_arrendamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Servicios Públicos Asegurados (Arrendamiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_servicios_publicos_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Servicios Públicos Asegurados (Cumplimiento)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_valor_vehiculos_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Vehículos Propios y No Propios Asegurados'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='numero_renovacion',
            field=models.CharField(default='RA-TEMP', max_length=50, verbose_name='Número de Renovación'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AddIndex(
            model_name='renovacionautomatica',
            index=models.Index(fields=['contrato', '-fecha_aprobacion', '-effective_from'], name='gestion_ren_contrat_a8ccb7_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacionautomatica',
            index=models.Index(fields=['contrato', 'estado', '-effective_from'], name='gestion_ren_contrat_181005_idx'),
        ),
    ]
