# Generated by Django 5.0.14 on 2025-12-08 21:10

from django.db import migrations, models
import django.db.models.deletion
from datetime import date, timedelta


def migrar_mes_a_fecha_contrato(apps, schema_editor):
    """Migra mes_aumento_ipc a fecha_aumento_ipc usando el día del mes de fecha_inicial_contrato"""
    Contrato = apps.get_model('gestion', 'Contrato')
    
    meses_dict = {
        'ENERO': 1, 'FEBRERO': 2, 'MARZO': 3, 'ABRIL': 4,
        'MAYO': 5, 'JUNIO': 6, 'JULIO': 7, 'AGOSTO': 8,
        'SEPTIEMBRE': 9, 'OCTUBRE': 10, 'NOVIEMBRE': 11, 'DICIEMBRE': 12
    }
    
    for contrato in Contrato.objects.filter(mes_aumento_ipc__isnull=False):
        if contrato.fecha_inicial_contrato:
            mes_num = meses_dict.get(contrato.mes_aumento_ipc, 1)
            # Usar el día del mes de la fecha inicial del contrato
            dia = contrato.fecha_inicial_contrato.day
            año = contrato.fecha_inicial_contrato.year
            
            # Crear fecha de aumento usando el mes del mes_aumento_ipc y el día de fecha_inicial_contrato
            try:
                fecha_aumento = date(año, mes_num, dia)
            except ValueError:
                # Si el día no existe en ese mes (ej: 31 de febrero), usar el último día del mes
                from calendar import monthrange
                ultimo_dia = monthrange(año, mes_num)[1]
                fecha_aumento = date(año, mes_num, ultimo_dia)
            
            contrato.fecha_aumento_ipc = fecha_aumento
            contrato.save()


def migrar_mes_a_fecha_otrosi(apps, schema_editor):
    """Migra nuevo_mes_aumento_ipc a nueva_fecha_aumento_ipc usando el día del mes de fecha_inicial_contrato del contrato"""
    OtroSi = apps.get_model('gestion', 'OtroSi')
    Contrato = apps.get_model('gestion', 'Contrato')
    
    meses_dict = {
        'ENERO': 1, 'FEBRERO': 2, 'MARZO': 3, 'ABRIL': 4,
        'MAYO': 5, 'JUNIO': 6, 'JULIO': 7, 'AGOSTO': 8,
        'SEPTIEMBRE': 9, 'OCTUBRE': 10, 'NOVIEMBRE': 11, 'DICIEMBRE': 12
    }
    
    for otrosi in OtroSi.objects.filter(nuevo_mes_aumento_ipc__isnull=False):
        contrato = otrosi.contrato
        if contrato and contrato.fecha_inicial_contrato:
            mes_num = meses_dict.get(otrosi.nuevo_mes_aumento_ipc, 1)
            dia = contrato.fecha_inicial_contrato.day
            año = contrato.fecha_inicial_contrato.year
            
            try:
                fecha_aumento = date(año, mes_num, dia)
            except ValueError:
                from calendar import monthrange
                ultimo_dia = monthrange(año, mes_num)[1]
                fecha_aumento = date(año, mes_num, ultimo_dia)
            
            otrosi.nueva_fecha_aumento_ipc = fecha_aumento
            otrosi.save()


def migrar_mes_a_fecha_calculo_ipc(apps, schema_editor):
    """Migra mes_aplicacion a fecha_aplicacion en CalculoIPC"""
    CalculoIPC = apps.get_model('gestion', 'CalculoIPC')
    
    meses_dict = {
        'ENERO': 1, 'FEBRERO': 2, 'MARZO': 3, 'ABRIL': 4,
        'MAYO': 5, 'JUNIO': 6, 'JULIO': 7, 'AGOSTO': 8,
        'SEPTIEMBRE': 9, 'OCTUBRE': 10, 'NOVIEMBRE': 11, 'DICIEMBRE': 12
    }
    
    for calculo in CalculoIPC.objects.all():
        if calculo.mes_aplicacion:
            mes_num = meses_dict.get(calculo.mes_aplicacion, 1)
            # Usar el día 1 del mes como fecha de aplicación (se puede ajustar después)
            fecha_aplicacion = date(calculo.año_aplicacion, mes_num, 1)
            calculo.fecha_aplicacion = fecha_aplicacion
            calculo.save()


def migrar_fecha_aumento_contrato_calculo_ipc(apps, schema_editor):
    """Migra mes_aumento_contrato a fecha_aumento_contrato en CalculoIPC"""
    CalculoIPC = apps.get_model('gestion', 'CalculoIPC')
    
    meses_dict = {
        'ENERO': 1, 'FEBRERO': 2, 'MARZO': 3, 'ABRIL': 4,
        'MAYO': 5, 'JUNIO': 6, 'JULIO': 7, 'AGOSTO': 8,
        'SEPTIEMBRE': 9, 'OCTUBRE': 10, 'NOVIEMBRE': 11, 'DICIEMBRE': 12
    }
    
    for calculo in CalculoIPC.objects.filter(mes_aumento_contrato__isnull=False):
        if calculo.mes_aumento_contrato:
            mes_num = meses_dict.get(calculo.mes_aumento_contrato, 1)
            contrato = calculo.contrato
            if contrato and contrato.fecha_inicial_contrato:
                dia = contrato.fecha_inicial_contrato.day
                año = calculo.año_aplicacion
                
                try:
                    fecha_aumento = date(año, mes_num, dia)
                except ValueError:
                    from calendar import monthrange
                    ultimo_dia = monthrange(año, mes_num)[1]
                    fecha_aumento = date(año, mes_num, ultimo_dia)
                
                calculo.fecha_aumento_contrato = fecha_aumento
                calculo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0050_actualizar_renovacion_automatica_como_evento'),
    ]

    operations = [
        # Renombrar fecha_aplicacion existente a fecha_aplicacion_real en CalculoIPC
        migrations.RenameField(
            model_name='calculoipc',
            old_name='fecha_aplicacion',
            new_name='fecha_aplicacion_real',
        ),
        
        # Agregar nuevos campos de fecha
        migrations.AddField(
            model_name='contrato',
            name='fecha_aumento_ipc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aumento IPC', help_text='Fecha exacta en que se aplica el ajuste por IPC (ej: si el contrato inicia el 15 de junio, el ajuste será el 15 de junio de cada año)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nueva_fecha_aumento_ipc',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Fecha Aumento IPC', help_text='Nueva fecha exacta en que se aplica el ajuste por IPC'),
        ),
        migrations.AddField(
            model_name='calculoipc',
            name='fecha_aplicacion',
            field=models.DateField(null=True, verbose_name='Fecha de Aplicación', help_text='Fecha exacta en que se aplica el ajuste por IPC'),
        ),
        migrations.AddField(
            model_name='calculoipc',
            name='fecha_aumento_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aumento del Contrato', help_text='Fecha exacta configurada en el contrato para el aumento por IPC'),
        ),
        
        # Migrar datos
        migrations.RunPython(migrar_mes_a_fecha_contrato, migrations.RunPython.noop),
        migrations.RunPython(migrar_mes_a_fecha_otrosi, migrations.RunPython.noop),
        migrations.RunPython(migrar_mes_a_fecha_calculo_ipc, migrations.RunPython.noop),
        migrations.RunPython(migrar_fecha_aumento_contrato_calculo_ipc, migrations.RunPython.noop),
        
        # Hacer fecha_aplicacion no nullable después de migrar datos
        migrations.AlterField(
            model_name='calculoipc',
            name='fecha_aplicacion',
            field=models.DateField(verbose_name='Fecha de Aplicación', help_text='Fecha exacta en que se aplica el ajuste por IPC'),
        ),
        
        # Agregar campos url_archivo
        migrations.AddField(
            model_name='contrato',
            name='url_archivo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Archivo Digital', help_text='Enlace al archivo digital del contrato (OneDrive, Google Drive, etc.)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='url_archivo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Archivo Digital', help_text='Enlace al archivo digital del Otro Sí (OneDrive, Google Drive, etc.)'),
        ),
        migrations.AddField(
            model_name='informeventas',
            name='url_archivo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Archivo Digital', help_text='Enlace al archivo digital del informe de ventas (OneDrive, Google Drive, etc.)'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='url_archivo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Archivo Digital', help_text='Enlace al archivo digital de la póliza (OneDrive, Google Drive, etc.)'),
        ),
        
        # Eliminar índices y unique_together que incluyen mes_aplicacion ANTES de eliminar el campo
        migrations.RemoveIndex(
            model_name='calculoipc',
            name='gestion_cal_contrat_123828_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calculoipc',
            unique_together=set(),
        ),
        
        # Eliminar campos antiguos de mes (después de migrar)
        migrations.RemoveField(
            model_name='contrato',
            name='mes_aumento_ipc',
        ),
        migrations.RemoveField(
            model_name='otrosi',
            name='nuevo_mes_aumento_ipc',
        ),
        migrations.RemoveField(
            model_name='calculoipc',
            name='mes_aplicacion',
        ),
        migrations.RemoveField(
            model_name='calculoipc',
            name='mes_aumento_contrato',
        ),
        
        # Actualizar índices y unique_together con los nuevos campos
        migrations.AlterUniqueTogether(
            name='calculoipc',
            unique_together={('contrato', 'fecha_aplicacion')},
        ),
    ]
