# Generated by Django 5.0.14 on 2025-12-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0051_cambiar_ipc_mes_a_fecha_y_agregar_url_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculoipc',
            options={'ordering': ['-fecha_aplicacion', '-fecha_calculo'], 'verbose_name': 'Cálculo de IPC', 'verbose_name_plural': 'Cálculos de IPC'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_clausula_proteccion_datos',
            field=models.BooleanField(default=False, verbose_name='Tiene Cláusula de Protección de Datos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_clausula_sarlaft',
            field=models.BooleanField(default=False, verbose_name='Tiene Cláusula SARLAFT'),
        ),
        migrations.AlterField(
            model_name='calculoipc',
            name='fecha_aplicacion_real',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se aplicó el cálculo', null=True, verbose_name='Fecha de Aplicación Real'),
        ),
        migrations.AlterField(
            model_name='calculoipc',
            name='periodicidad_contrato',
            field=models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('FECHA_ESPECIFICA', 'Fecha Específica')], help_text='Periodicidad configurada en el contrato', max_length=20, null=True, verbose_name='Periodicidad del Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='periodicidad_ipc',
            field=models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('FECHA_ESPECIFICA', 'Fecha Específica')], max_length=20, null=True, verbose_name='Periodicidad IPC'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nueva_periodicidad_ipc',
            field=models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('FECHA_ESPECIFICA', 'Fecha Específica')], max_length=20, null=True, verbose_name='Nueva Periodicidad IPC'),
        ),
        migrations.AddIndex(
            model_name='calculoipc',
            index=models.Index(fields=['contrato', 'fecha_aplicacion'], name='gestion_cal_contrat_f454bc_idx'),
        ),
    ]
