# Generated by Django 5.0.14 on 2025-12-08 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0052_add_clausulas_sarlaft_proteccion_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('tipo_alerta', models.CharField(choices=[('VENCIMIENTO_CONTRATOS', 'Vencimiento de Contratos'), ('ALERTAS_IPC', 'Alertas IPC'), ('POLIZAS_CRITICAS', 'Pólizas Críticas'), ('PREAVISO_RENOVACION', 'Preaviso de Renovación'), ('POLIZAS_REQUERIDAS', 'Pólizas Requeridas No Aportadas'), ('TERMINACION_ANTICIPADA', 'Terminación Anticipada'), ('RENOVACION_AUTOMATICA', 'Renovación Automática')], help_text='Tipo de alerta a configurar', max_length=50, unique=True, verbose_name='Tipo de Alerta')),
                ('activo', models.BooleanField(default=True, help_text='Activar o desactivar este tipo de alerta', verbose_name='Alerta Activa')),
                ('frecuencia', models.CharField(choices=[('INMEDIATO', 'Inmediato'), ('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='SEMANAL', help_text='Con qué frecuencia se enviará esta alerta', max_length=20, verbose_name='Frecuencia de Envío')),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='Días de la semana para envío (0=Lunes, 6=Domingo). Solo aplica para frecuencia semanal.', verbose_name='Días de la Semana')),
                ('hora_envio', models.TimeField(default='08:00', help_text='Hora del día para enviar las alertas', verbose_name='Hora de Envío')),
                ('solo_criticas', models.BooleanField(default=False, help_text='Enviar solo alertas de nivel crítico (danger)', verbose_name='Solo Alertas Críticas')),
                ('asunto', models.CharField(blank=True, help_text='Asunto del correo (dejar vacío para usar asunto por defecto)', max_length=200, null=True, verbose_name='Asunto Personalizado')),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alertas',
                'ordering': ['tipo_alerta'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar esta configuración', max_length=100, verbose_name='Nombre de la Configuración')),
                ('email_host', models.CharField(help_text='Ejemplo: smtp.gmail.com', max_length=255, verbose_name='Servidor SMTP')),
                ('email_port', models.IntegerField(default=587, help_text='Puerto del servidor SMTP (587 para TLS, 465 para SSL)', verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Activar si el servidor requiere TLS', verbose_name='Usar TLS')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Activar si el servidor requiere SSL', verbose_name='Usar SSL')),
                ('email_host_user', models.EmailField(help_text='Email o usuario para autenticación SMTP', max_length=254, verbose_name='Usuario/Email')),
                ('email_host_password', models.TextField(help_text='Contraseña o token de aplicación (encriptada automáticamente)', verbose_name='Contraseña Encriptada')),
                ('email_from', models.EmailField(help_text='Email que aparecerá como remitente', max_length=254, verbose_name='Email Remitente')),
                ('nombre_remitente', models.CharField(blank=True, help_text='Nombre que aparecerá junto al email remitente', max_length=200, null=True, verbose_name='Nombre del Remitente')),
                ('activo', models.BooleanField(default=True, help_text='Solo una configuración puede estar activa', verbose_name='Configuración Activa')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('tipo_alerta', models.CharField(choices=[('VENCIMIENTO_CONTRATOS', 'Vencimiento de Contratos'), ('ALERTAS_IPC', 'Alertas IPC'), ('POLIZAS_CRITICAS', 'Pólizas Críticas'), ('PREAVISO_RENOVACION', 'Preaviso de Renovación'), ('POLIZAS_REQUERIDAS', 'Pólizas Requeridas No Aportadas'), ('TERMINACION_ANTICIPADA', 'Terminación Anticipada'), ('RENOVACION_AUTOMATICA', 'Renovación Automática')], max_length=50, verbose_name='Tipo de Alerta')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Email Destinatario')),
                ('asunto', models.CharField(max_length=500, verbose_name='Asunto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si el envío falló', null=True, verbose_name='Mensaje de Error')),
                ('cantidad_alertas', models.IntegerField(default=0, help_text='Cantidad de alertas incluidas en el correo', verbose_name='Cantidad de Alertas')),
            ],
            options={
                'verbose_name': 'Historial de Envío de Email',
                'verbose_name_plural': 'Historial de Envíos de Email',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo_alerta', '-fecha_creacion'], name='gestion_his_tipo_al_277a6f_idx'), models.Index(fields=['estado', '-fecha_creacion'], name='gestion_his_estado_459a2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Destinatario')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del destinatario', max_length=200, null=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('configuracion_alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='gestion.configuracionalerta', verbose_name='Configuración de Alerta')),
            ],
            options={
                'verbose_name': 'Destinatario de Alerta',
                'verbose_name_plural': 'Destinatarios de Alertas',
                'ordering': ['configuracion_alerta', 'email'],
                'unique_together': {('configuracion_alerta', 'email')},
            },
        ),
    ]
