# Generated by Django 5.0.14 on 2025-12-26 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrar_arrendatarios_a_terceros(apps, schema_editor):
    """Migra los datos de Arrendatario a Tercero con tipo='ARRENDATARIO'"""
    Arrendatario = apps.get_model('gestion', 'Arrendatario')
    Tercero = apps.get_model('gestion', 'Tercero')
    
    for arrendatario in Arrendatario.objects.all():
        Tercero.objects.create(
            id=arrendatario.id,
            nit=arrendatario.nit,
            razon_social=arrendatario.razon_social,
            tipo='ARRENDATARIO',
            nombre_rep_legal=arrendatario.nombre_rep_legal,
            nombre_supervisor_op=arrendatario.nombre_supervisor_op,
            email_supervisor_op=arrendatario.email_supervisor_op,
            creado_por=arrendatario.creado_por,
            fecha_creacion=arrendatario.fecha_creacion,
            modificado_por=arrendatario.modificado_por,
            fecha_modificacion=arrendatario.fecha_modificacion,
            eliminado_por=arrendatario.eliminado_por,
            fecha_eliminacion=arrendatario.fecha_eliminacion,
        )


def revertir_migracion_terceros_a_arrendatarios(apps, schema_editor):
    """Revierte la migración: convierte Terceros tipo ARRENDATARIO de vuelta a Arrendatario"""
    Arrendatario = apps.get_model('gestion', 'Arrendatario')
    Tercero = apps.get_model('gestion', 'Tercero')
    
    for tercero in Tercero.objects.filter(tipo='ARRENDATARIO'):
        Arrendatario.objects.create(
            id=tercero.id,
            nit=tercero.nit,
            razon_social=tercero.razon_social,
            nombre_rep_legal=tercero.nombre_rep_legal,
            nombre_supervisor_op=tercero.nombre_supervisor_op,
            email_supervisor_op=tercero.email_supervisor_op,
            creado_por=tercero.creado_por,
            fecha_creacion=tercero.fecha_creacion,
            modificado_por=tercero.modificado_por,
            fecha_modificacion=tercero.fecha_modificacion,
            eliminado_por=tercero.eliminado_por,
            fecha_eliminacion=tercero.fecha_eliminacion,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0053_cambiar_email_password_a_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('tipo', models.CharField(choices=[('ARRENDATARIO', 'Arrendatario'), ('PROVEEDOR', 'Proveedor')], default='ARRENDATARIO', max_length=20, verbose_name='Tipo de Tercero')),
                ('nombre_rep_legal', models.CharField(max_length=100, verbose_name='Nombre Representante Legal')),
                ('nombre_supervisor_op', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Supervisor Operativo')),
                ('email_supervisor_op', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Supervisor Operativo')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['razon_social'],
            },
        ),
        migrations.RunPython(migrar_arrendatarios_a_terceros, revertir_migracion_terceros_a_arrendatarios),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato_cliente_proveedor',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], default='CLIENTE', max_length=20, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.local', verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion.tipocontrato', verbose_name='Tipo de Contrato (Cliente)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_proveedor', to='gestion.tercero', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_arrendatario', to='gestion.tercero', verbose_name='Arrendatario'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion.tiposervicio', verbose_name='Tipo de Servicio (Proveedor)'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: None,  # No hacer nada en forward
            lambda apps, schema_editor: None   # No hacer nada en reverse
        ),
        migrations.DeleteModel(
            name='Arrendatario',
        ),
    ]
