# Generated by Django 5.0.14 on 2025-12-26 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0054_renombrar_arrendatario_a_tercero_y_agregar_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='porcentaje_salario_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje del Salario Mínimo Legal Vigente a aplicar (solo para contratos con tipo SALARIO_MINIMO)', max_digits=6, null=True, verbose_name='Porcentaje Salario Mínimo (%)'),
        ),
        migrations.CreateModel(
            name='SalarioMinimoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(help_text='Año del Salario Mínimo Legal Vigente', unique=True, verbose_name='Año')),
                ('valor_salario_minimo', models.DecimalField(decimal_places=2, help_text='Valor del Salario Mínimo Legal Vigente en pesos colombianos', max_digits=12, verbose_name='Valor Salario Mínimo ($)')),
                ('fecha_decreto', models.DateField(blank=True, help_text='Fecha en que se decretó este valor', null=True, verbose_name='Fecha de Decreto')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este valor de Salario Mínimo', null=True, verbose_name='Observaciones')),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Salario Mínimo Histórico',
                'verbose_name_plural': 'Salario Mínimo Histórico',
                'ordering': ['-año'],
                'indexes': [models.Index(fields=['año'], name='gestion_sal_año_4ec9be_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalculoSalarioMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_aplicacion', models.IntegerField(help_text='Año para el cual se aplica el ajuste por Salario Mínimo', verbose_name='Año de Aplicación')),
                ('fecha_aplicacion', models.DateField(help_text='Fecha exacta en que se aplica el ajuste por Salario Mínimo', verbose_name='Fecha de Aplicación')),
                ('canon_anterior', models.DecimalField(decimal_places=2, help_text='Canon base sobre el cual se calcula el ajuste', max_digits=20, verbose_name='Canon Anterior')),
                ('canon_anterior_manual', models.BooleanField(default=False, help_text='Indica si el canon anterior fue ingresado manualmente', verbose_name='Canon Anterior Manual')),
                ('fuente_canon_anterior', models.CharField(blank=True, help_text='Indica de dónde proviene el canon anterior (Otro Sí, cálculo previo, manual)', max_length=100, null=True, verbose_name='Fuente del Canon Anterior')),
                ('porcentaje_salario_minimo', models.DecimalField(decimal_places=2, help_text='Porcentaje del Salario Mínimo pactado en el contrato', max_digits=6, verbose_name='Porcentaje Salario Mínimo (%)')),
                ('puntos_adicionales', models.DecimalField(decimal_places=2, default=0, help_text='Puntos adicionales pactados en el contrato', max_digits=5, verbose_name='Puntos Adicionales (%)')),
                ('porcentaje_total_aplicar', models.DecimalField(decimal_places=2, help_text='Porcentaje Salario Mínimo + Puntos Adicionales', max_digits=6, verbose_name='Porcentaje Total a Aplicar (%)')),
                ('valor_incremento', models.DecimalField(decimal_places=2, help_text='Valor en pesos del incremento', max_digits=20, verbose_name='Valor del Incremento')),
                ('nuevo_canon', models.DecimalField(decimal_places=2, help_text='Canon Anterior * (1 + (Porcentaje Salario Mínimo + Puntos Adicionales)/100)', max_digits=20, verbose_name='Nuevo Canon')),
                ('periodicidad_contrato', models.CharField(blank=True, choices=[('ANUAL', 'Anual'), ('FECHA_ESPECIFICA', 'Fecha Específica')], help_text='Periodicidad configurada en el contrato', max_length=20, null=True, verbose_name='Periodicidad del Contrato')),
                ('fecha_aumento_contrato', models.DateField(blank=True, help_text='Fecha exacta configurada en el contrato para el aumento por Salario Mínimo', null=True, verbose_name='Fecha de Aumento del Contrato')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este cálculo', null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('calculado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calculado Por')),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Cálculo')),
                ('aplicado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Aplicado Por')),
                ('fecha_aplicacion_real', models.DateTimeField(blank=True, help_text='Fecha y hora en que se aplicó el cálculo', null=True, verbose_name='Fecha de Aplicación Real')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_salario_minimo', to='gestion.contrato', verbose_name='Contrato')),
                ('salario_minimo_historico', models.ForeignKey(help_text='Valor del Salario Mínimo Legal Vigente para este año', on_delete=django.db.models.deletion.PROTECT, related_name='calculos_salario_minimo', to='gestion.salariominimohistorico', verbose_name='Salario Mínimo Histórico')),
            ],
            options={
                'verbose_name': 'Cálculo de Salario Mínimo',
                'verbose_name_plural': 'Cálculos de Salario Mínimo',
                'ordering': ['-fecha_aplicacion', '-fecha_calculo'],
                'indexes': [models.Index(fields=['contrato', 'fecha_aplicacion'], name='gestion_cal_contrat_6b9b9d_idx'), models.Index(fields=['estado'], name='gestion_cal_estado_ca10ec_idx'), models.Index(fields=['fecha_calculo'], name='gestion_cal_fecha_c_696a0f_idx')],
                'unique_together': {('contrato', 'fecha_aplicacion')},
            },
        ),
    ]
