# Generated by Django 5.0.14 on 2025-12-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_agregar_campos_polizas_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_amortizacion_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Correcta amortización del anticipo (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_aportes_seguridad_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Aportes al sistema de seguridad social'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_buen_manejo_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Buen manejo y correcta inversión del anticipo (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_calidad_bienes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Calidad y correcto funcionamiento de bienes (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_calidad_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Calidad del servicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_clausula_penal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cláusula penal pecuniaria (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_cumplimiento_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cumplimiento del contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_estabilidad_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Estabilidad de la obra (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_multas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Multas (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_salarios_prestaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Salarios, prestaciones sociales e indemnizaciones laborales'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cumplimiento_amparo_sanciones_incumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Sanciones por incumplimiento (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_danos_bienes_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Daños a bienes de terceros'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_danos_contratistas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Daños causados por contratistas y subcontratistas (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_danos_ejecucion_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Daños durante la ejecución del contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_danos_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Daños materiales a terceros'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_danos_predios_vecinos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Daños en predios vecinos (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_gastos_defensa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Gastos de defensa (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_gastos_medicos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Gastos médicos (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_lesiones_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Lesiones personales a terceros'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_muerte_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Muerte de terceros'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_perjuicios_patrimoniales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Perjuicios patrimoniales consecuenciales (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_responsabilidad_cruzada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Responsabilidad cruzada (si aplica)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rce_cobertura_responsabilidad_patronal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Responsabilidad patronal (si aplica)'),
        ),
    ]
