# Generated by Django 5.0.14 on 2025-12-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_agregar_campos_poliza_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_amortizacion_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Correcta amortización del anticipo (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_aportes_seguridad_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Aportes al sistema de seguridad social'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_buen_manejo_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Buen manejo y correcta inversión del anticipo (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_calidad_bienes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Calidad y correcto funcionamiento de bienes (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_calidad_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Calidad del servicio'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_clausula_penal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Cláusula penal pecuniaria (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_cumplimiento_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Cumplimiento del contrato'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_estabilidad_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Estabilidad de la obra (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_multas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Multas (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_salarios_prestaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Salarios, prestaciones sociales e indemnizaciones laborales'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_cumplimiento_amparo_sanciones_incumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Sanciones por incumplimiento (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_danos_bienes_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños a bienes de terceros'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_danos_contratistas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños causados por contratistas y subcontratistas (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_danos_ejecucion_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños durante la ejecución del contrato'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_danos_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños materiales a terceros'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_danos_predios_vecinos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños en predios vecinos (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_gastos_defensa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Gastos de defensa (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_gastos_medicos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Gastos médicos (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_lesiones_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Lesiones personales a terceros'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_muerte_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Muerte de terceros'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_perjuicios_patrimoniales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Perjuicios patrimoniales consecuenciales (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_responsabilidad_cruzada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Responsabilidad cruzada (si aplica)'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='nuevo_rce_cobertura_responsabilidad_patronal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Responsabilidad patronal (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_amortizacion_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Correcta amortización del anticipo (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_aportes_seguridad_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Aportes al sistema de seguridad social'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_buen_manejo_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Buen manejo y correcta inversión del anticipo (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_calidad_bienes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Calidad y correcto funcionamiento de bienes (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_calidad_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Calidad del servicio'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_clausula_penal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Cláusula penal pecuniaria (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_cumplimiento_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Cumplimiento del contrato'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_estabilidad_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Estabilidad de la obra (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_multas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Multas (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_salarios_prestaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Salarios, prestaciones sociales e indemnizaciones laborales'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_cumplimiento_amparo_sanciones_incumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Sanciones por incumplimiento (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_danos_bienes_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños a bienes de terceros'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_danos_contratistas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños causados por contratistas y subcontratistas (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_danos_ejecucion_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños durante la ejecución del contrato'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_danos_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños materiales a terceros'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_danos_predios_vecinos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Daños en predios vecinos (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_gastos_defensa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Gastos de defensa (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_gastos_medicos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Gastos médicos (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_lesiones_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Lesiones personales a terceros'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_muerte_terceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Muerte de terceros'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_perjuicios_patrimoniales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Perjuicios patrimoniales consecuenciales (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_responsabilidad_cruzada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Responsabilidad cruzada (si aplica)'),
        ),
        migrations.AddField(
            model_name='renovacionautomatica',
            name='nuevo_rce_cobertura_responsabilidad_patronal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo Responsabilidad patronal (si aplica)'),
        ),
    ]
