# Generated by Django 5.0.14 on 2025-12-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0059_agregar_campos_polizas_proveedor_otrosi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='supervisor_concesionario',
            new_name='supervisor_contraparte',
        ),
    ]
