# Generated by Django 5.0.14 on 2025-12-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0060_renombrar_supervisor_concesionario_a_contraparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='salariominimohistorico',
            name='variacion_porcentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variación porcentual calculada automáticamente comparando con el año anterior', max_digits=6, null=True, verbose_name='Variación Porcentual (%)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='supervisor_contraparte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor Contraparte'),
        ),
    ]
