# Generated by Django 5.0.14 on 2025-12-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0061_agregar_variacion_porcentual_salario_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salariominimohistorico',
            name='variacion_porcentual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Variación porcentual calculada automáticamente comparando con el año anterior', max_digits=10, null=True, verbose_name='Variación Porcentual (%)'),
        ),
    ]
