# Generated by Django 5.0.14 on 2026-01-17 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0062_ajustar_variacion_porcentual_salario_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Cláusula')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Cláusula',
                'verbose_name_plural': 'Cláusulas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ClausulaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('clausula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion.clausula', verbose_name='Cláusula')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='gestion.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Cláusula de Contrato',
                'verbose_name_plural': 'Cláusulas de Contratos',
                'ordering': ['contrato', 'clausula'],
                'unique_together': {('contrato', 'clausula')},
            },
        ),
        migrations.CreateModel(
            name='ClausulaObligatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=150, null=True, verbose_name='Creado Por')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=150, null=True, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de Modificación')),
                ('eliminado_por', models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True, verbose_name='Eliminado Por')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del registro', null=True, verbose_name='Fecha de Eliminación')),
                ('tipo_contrato_cliente_proveedor', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=20, verbose_name='Tipo de Contrato')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('clausula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligatorias', to='gestion.clausula', verbose_name='Cláusula')),
                ('tipo_contrato', models.ForeignKey(blank=True, help_text='Si se deja vacío, aplica a todos los tipos de cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clausulas_obligatorias', to='gestion.tipocontrato', verbose_name='Tipo de Contrato (Cliente)')),
                ('tipo_servicio', models.ForeignKey(blank=True, help_text='Si se deja vacío, aplica a todos los tipos de proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clausulas_obligatorias', to='gestion.tiposervicio', verbose_name='Tipo de Servicio (Proveedor)')),
            ],
            options={
                'verbose_name': 'Cláusula Obligatoria',
                'verbose_name_plural': 'Cláusulas Obligatorias',
                'ordering': ['tipo_contrato_cliente_proveedor', 'tipo_contrato', 'tipo_servicio', 'clausula'],
                'unique_together': {('clausula', 'tipo_contrato_cliente_proveedor', 'tipo_contrato', 'tipo_servicio')},
            },
        ),
    ]
