# Generated by Django 5.0.14 on 2026-01-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0063_agregar_modelos_clausulas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clausula',
            name='descripcion',
        ),
    ]
