# Generated by Django 5.0.14 on 2026-01-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0064_eliminar_descripcion_clausula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AddConstraint(
            model_name='tercero',
            constraint=models.UniqueConstraint(fields=('nit', 'tipo'), name='unique_nit_por_tipo'),
        ),
    ]
