# Generated by Django 5.0.14 on 2026-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0065_permitir_mismo_nit_cliente_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('VENCIMIENTO_CONTRATOS', 'Vencimiento de Contratos'), ('ALERTAS_IPC', 'Alertas IPC'), ('ALERTAS_SALARIO_MINIMO', 'Alertas de Ajuste de Salario Mínimo'), ('POLIZAS_CRITICAS', 'Pólizas Críticas'), ('PREAVISO_RENOVACION', 'Preaviso de Renovación'), ('POLIZAS_REQUERIDAS', 'Pólizas Requeridas No Aportadas'), ('TERMINACION_ANTICIPADA', 'Terminación Anticipada'), ('RENOVACION_AUTOMATICA', 'Renovación Automática')], help_text='Tipo de alerta a configurar', max_length=50, unique=True, verbose_name='Tipo de Alerta'),
        ),
        migrations.AlterField(
            model_name='historialenvioemail',
            name='tipo_alerta',
            field=models.CharField(choices=[('VENCIMIENTO_CONTRATOS', 'Vencimiento de Contratos'), ('ALERTAS_IPC', 'Alertas IPC'), ('ALERTAS_SALARIO_MINIMO', 'Alertas de Ajuste de Salario Mínimo'), ('POLIZAS_CRITICAS', 'Pólizas Críticas'), ('PREAVISO_RENOVACION', 'Preaviso de Renovación'), ('POLIZAS_REQUERIDAS', 'Pólizas Requeridas No Aportadas'), ('TERMINACION_ANTICIPADA', 'Terminación Anticipada'), ('RENOVACION_AUTOMATICA', 'Renovación Automática')], max_length=50, verbose_name='Tipo de Alerta'),
        ),
    ]
