# Generated by Django 5.0.14 on 2026-02-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0066_alter_configuracionalerta_tipo_alerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='documento_origen_tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato Base'), ('OTROSI', 'Otro Sí'), ('RENOVACION', 'Renovación Automática')], default='CONTRATO', help_text='Tipo de documento al que pertenece esta póliza', max_length=20, verbose_name='Tipo de Documento Origen'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_vencimiento_real',
            field=models.DateField(blank=True, help_text='Fecha real de vencimiento (sin colchón). Se calcula automáticamente basada en la fecha final del contrato.', null=True, verbose_name='Fecha Vencimiento Real'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='meses_colchon',
            field=models.IntegerField(blank=True, default=0, help_text='Meses adicionales agregados como colchón de seguridad', null=True, verbose_name='Meses Colchón'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_automatica',
            field=models.ForeignKey(blank=True, help_text='Renovación Automática a la que pertenece esta póliza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='gestion.renovacionautomatica', verbose_name='Renovación Automática'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='tiene_colchon',
            field=models.BooleanField(default=False, help_text='Indica si esta póliza tiene meses adicionales como colchón de seguridad', verbose_name='Tiene Colchón'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='otrosi',
            field=models.ForeignKey(blank=True, help_text='Otro Sí al que pertenece esta póliza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='gestion.otrosi', verbose_name='Otro Sí'),
        ),
    ]
