# Generated by Django 5.0.14 on 2026-02-28 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0067_agregar_historial_y_colchon_polizas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['-fecha_vencimiento'], 'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AddField(
            model_name='calculofacturacionventas',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Cuando está confirmado, los campos de % ventas y canon mínimo quedan bloqueados en el contrato.', verbose_name='Confirmado'),
        ),
        migrations.AddField(
            model_name='calculofacturacionventas',
            name='confirmado_por',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='calculofacturacionventas',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AlterField(
            model_name='configuracionemail',
            name='email_host_password',
            field=models.TextField(help_text='Contraseña o token de aplicación (encriptada automáticamente). Para Gmail: Debe usar una "Contraseña de aplicación" en lugar de su contraseña normal. Obténgala en: https://myaccount.google.com/apppasswords', verbose_name='Contraseña Encriptada'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nit_concedente',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rep_legal_concedente',
            field=models.CharField(max_length=100, verbose_name='Representante Legal'),
        ),
        migrations.CreateModel(
            name='DependenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueador_tipo', models.CharField(choices=[('OTROSI', 'Otro Sí'), ('RENOVACION', 'Renovación Automática'), ('CALCULO_IPC', 'Cálculo IPC'), ('CALCULO_SMLV', 'Cálculo SMLV'), ('CALCULO_VENTAS', 'Cálculo de Facturación por Ventas')], max_length=20, verbose_name='Tipo Bloqueador')),
                ('bloqueador_id', models.PositiveIntegerField(verbose_name='ID Bloqueador')),
                ('bloqueador_descripcion', models.CharField(help_text='Texto legible: "OtroSí #2 — Canon $5.200.000 — Aprobado 15/01/2025"', max_length=300, verbose_name='Descripción del Bloqueador')),
                ('bloqueador_url', models.CharField(blank=True, help_text='URL relativa para ir directamente al documento bloqueador', max_length=300, verbose_name='URL del Bloqueador')),
                ('bloqueado_tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('OTROSI', 'Otro Sí')], max_length=20, verbose_name='Tipo Bloqueado')),
                ('bloqueado_id', models.PositiveIntegerField(verbose_name='ID Bloqueado')),
                ('campo_bloqueado', models.CharField(help_text='Nombre interno del campo (ej: valor_canon_fijo)', max_length=100, verbose_name='Campo Bloqueado')),
                ('label_campo', models.CharField(blank=True, max_length=200, verbose_name='Etiqueta del Campo')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Dependencia de Documento',
                'verbose_name_plural': 'Dependencias de Documentos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['bloqueado_tipo', 'bloqueado_id'], name='gestion_dep_bloquea_4a689c_idx'), models.Index(fields=['bloqueador_tipo', 'bloqueador_id'], name='gestion_dep_bloquea_958572_idx'), models.Index(fields=['campo_bloqueado'], name='gestion_dep_campo_b_8f3db5_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialCampoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(help_text='CONTRATO | OTROSI | RENOVACION', max_length=30, verbose_name='Tipo de Documento')),
                ('documento_id', models.PositiveIntegerField(verbose_name='ID del Documento')),
                ('documento_descripcion', models.CharField(blank=True, help_text='Texto legible: número de contrato, número de OtroSí, etc.', max_length=300, verbose_name='Descripción del Documento')),
                ('nombre_campo', models.CharField(help_text='Nombre interno del campo (ej: valor_canon_fijo)', max_length=100, verbose_name='Campo Modificado')),
                ('label_campo', models.CharField(blank=True, help_text='Nombre legible del campo (ej: Valor Canon Fijo)', max_length=200, verbose_name='Etiqueta del Campo')),
                ('valor_anterior', models.JSONField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.JSONField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('modificado_por', models.CharField(max_length=150, verbose_name='Modificado Por')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Modificación')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('causa_tipo', models.CharField(choices=[('EDICION_DIRECTA', 'Edición directa'), ('APROBACION_OTROSI', 'Aprobación de Otro Sí'), ('ELIMINACION_OTROSI', 'Eliminación de Otro Sí'), ('APROBACION_RENOVACION', 'Aprobación de Renovación Automática'), ('ELIMINACION_RENOVACION', 'Eliminación de Renovación Automática'), ('APLICACION_CALCULO_IPC', 'Aplicación de Cálculo IPC'), ('APLICACION_CALCULO_SMLV', 'Aplicación de Cálculo SMLV'), ('CONFIRMACION_CALCULO_VENTAS', 'Confirmación de Cálculo de Ventas')], max_length=40, verbose_name='Causa del Cambio')),
                ('causa_descripcion', models.CharField(blank=True, help_text='Texto legible de qué causó el cambio', max_length=300, verbose_name='Descripción de la Causa')),
            ],
            options={
                'verbose_name': 'Historial de Campo',
                'verbose_name_plural': 'Historial de Campos',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['tipo_documento', 'documento_id'], name='gestion_his_tipo_do_b5b69f_idx'), models.Index(fields=['nombre_campo'], name='gestion_his_nombre__c09a97_idx'), models.Index(fields=['modificado_por'], name='gestion_his_modific_bd508c_idx'), models.Index(fields=['-fecha_modificacion'], name='gestion_his_fecha_m_2a8b4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin_general', models.BooleanField(default=False, help_text='Marca al usuario como Admin General. Solo puede haber uno activo.', verbose_name='Es Admin General')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
