# Generated by Django 5.0.14 on 2026-03-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0068_cadena_efecto_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoipc',
            name='legalizado_via_otrosi',
            field=models.BooleanField(default=False, help_text='Indica que el ajuste fue legalizado usando un Otro Sí existente', verbose_name='Legalizado vía Otro Sí'),
        ),
        migrations.AddField(
            model_name='calculoipc',
            name='otrosi_referencia',
            field=models.ForeignKey(blank=True, help_text='Otro Sí que sirvió como evidencia del ajuste por IPC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_ipc_referencia', to='gestion.otrosi', verbose_name='Otro Sí referenciado'),
        ),
        migrations.AddField(
            model_name='calculosalariominimo',
            name='legalizado_via_otrosi',
            field=models.BooleanField(default=False, help_text='Indica que el ajuste fue legalizado usando un Otro Sí existente', verbose_name='Legalizado vía Otro Sí'),
        ),
        migrations.AddField(
            model_name='calculosalariominimo',
            name='otrosi_referencia',
            field=models.ForeignKey(blank=True, help_text='Otro Sí que sirvió como evidencia del ajuste por Salario Mínimo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_smlv_referencia', to='gestion.otrosi', verbose_name='Otro Sí referenciado'),
        ),
    ]
