# Generated by Django 5.0.14 on 2026-03-14 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0071_otrosi_prorroga_automatica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='finalizado',
            field=models.BooleanField(default=False, help_text='Indica que el contrato fue terminado formalmente mediante acto administrativo.', verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='fecha_inicio_prorroga_automatica',
            field=models.DateField(blank=True, help_text='Se auto-llena desde effective_from al guardar. Es el punto de partida para calcular renovaciones futuras.', null=True, verbose_name='Fecha de Inicio de Prórroga Automática'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='nueva_duracion_renovacion_meses',
            field=models.IntegerField(blank=True, help_text='Duración de cada ciclo de renovación automática a partir de este OtroSí. Si se omite, se usa la duración inicial del contrato.', null=True, verbose_name='Nueva Duración de Renovación (Meses)'),
        ),
        migrations.CreateModel(
            name='FinalizacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('CUMPLIMIENTO_PLAZO', 'Cumplimiento del Plazo Contractual'), ('MUTUO_ACUERDO', 'Mutuo Acuerdo entre las Partes'), ('INCUMPLIMIENTO', 'Incumplimiento Contractual'), ('LIQUIDACION', 'Liquidación del Contrato'), ('RESCISION', 'Rescisión Unilateral'), ('CESION', 'Cesión o Subrogación del Contrato'), ('FUERZA_MAYOR', 'Fuerza Mayor o Caso Fortuito'), ('OTRO', 'Otro Motivo')], max_length=30, verbose_name='Motivo de Terminación')),
                ('fecha_finalizacion', models.DateField(help_text='Fecha oficial en la que el contrato queda terminado. El contrato aparecerá como "Terminado" a partir de este día.', verbose_name='Fecha de Terminación')),
                ('numero_acta', models.CharField(blank=True, help_text='Número del acta de liquidación, comunicado u otro documento que formaliza la terminación.', max_length=100, verbose_name='N.° de Acta / Documento de Soporte')),
                ('acuerdo_partes', models.BooleanField(default=False, help_text='Indica que ambas partes manifestaron su conformidad con la terminación.', verbose_name='Acuerdo entre las Partes')),
                ('visto_bueno_gerencia', models.BooleanField(default=False, verbose_name='Visto Bueno de Gerencia')),
                ('nombre_gerente', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Gerente que aprueba')),
                ('fecha_vb_gerencia', models.DateField(blank=True, null=True, verbose_name='Fecha Visto Bueno Gerencia')),
                ('visto_bueno_juridica', models.BooleanField(default=False, verbose_name='Visto Bueno de Jurídica')),
                ('nombre_juridica', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Responsable Jurídico que aprueba')),
                ('fecha_vb_juridica', models.DateField(blank=True, null=True, verbose_name='Fecha Visto Bueno Jurídica')),
                ('detalles', models.TextField(help_text='Descripción detallada de las circunstancias, acuerdos y condiciones bajo las cuales se termina el contrato.', verbose_name='Detalles de la Terminación')),
                ('observaciones_legales', models.TextField(blank=True, help_text='Obligaciones residuales, compromisos de confidencialidad, devolución de activos u otras notas legales relevantes.', verbose_name='Observaciones Legales / Compromisos Post-Terminación')),
                ('url_documento_soporte', models.URLField(blank=True, help_text='Enlace al acta, comunicado u otro documento digital que soporta la terminación.', null=True, verbose_name='URL Documento de Soporte')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finalizacion', to='gestion.contrato', verbose_name='Contrato')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalizaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Finalización de Contrato',
                'verbose_name_plural': 'Finalizaciones de Contratos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
