# Generated by Django 5.0.14 on 2026-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0072_finalizacion_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='url_archivo',
            field=models.CharField(blank=True, help_text='Enlace al archivo digital del contrato (OneDrive, Google Drive, etc.)', max_length=500, null=True, verbose_name='URL del Archivo Digital'),
        ),
        migrations.AlterField(
            model_name='finalizacioncontrato',
            name='url_documento_soporte',
            field=models.CharField(blank=True, help_text='Enlace al acta, comunicado u otro documento digital que soporta la terminación.', max_length=500, null=True, verbose_name='URL Documento de Soporte'),
        ),
        migrations.AlterField(
            model_name='informeventas',
            name='url_archivo',
            field=models.CharField(blank=True, help_text='Enlace al archivo digital del informe de ventas (OneDrive, Google Drive, etc.)', max_length=500, null=True, verbose_name='URL del Archivo Digital'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='url_archivo',
            field=models.CharField(blank=True, help_text='Enlace al archivo digital del Otro Sí (OneDrive, Google Drive, etc.)', max_length=500, null=True, verbose_name='URL del Archivo Digital'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='url_archivo',
            field=models.CharField(blank=True, help_text='Enlace al archivo digital de la póliza (OneDrive, Google Drive, etc.)', max_length=500, null=True, verbose_name='URL del Archivo Digital'),
        ),
    ]
