# Generated by Django 5.0.14 on 2026-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0073_urlfield_to_charfield_url_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='clausula_penal_incumplimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula Penal por Incumplimiento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='multa_mora_no_restitucion',
            field=models.TextField(blank=True, null=True, verbose_name='Multa por Mora en No Restitución'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='penalidad_terminacion_anticipada',
            field=models.TextField(blank=True, null=True, verbose_name='Penalidad por Terminación Anticipada'),
        ),
    ]
