# Generated by Django 5.0.11 on 2026-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0075_renombrar_amparos_rce_proveedor_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculofacturacionventas',
            name='url_archivo',
            field=models.CharField(blank=True, help_text='Enlace al archivo digital de soporte del cálculo (OneDrive, Google Drive, etc.)', max_length=500, null=True, verbose_name='URL del Archivo Digital'),
        ),
    ]
