# Generated by Django 5.0.11 on 2026-06-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0076_agregar_url_archivo_calculo_facturacion_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculofacturacionventas',
            name='informe_ventas',
            field=models.ForeignKey(blank=True, help_text='Informe de ventas asociado (opcional). Al eliminar el informe se elimina también este cálculo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculos_facturacion', to='gestion.informeventas', verbose_name='Informe de Ventas'),
        ),
    ]
