# Generated by Django 5.0.11 on 2026-06-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0077_cascade_eliminar_calculo_al_eliminar_informe_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculofacturacionventas',
            name='fuente_canon_fijo',
            field=models.CharField(blank=True, help_text='De dónde se tomó el Canon Fijo vigente (Otro Sí, Cálculo IPC/Salario Mínimo o Contrato base)', max_length=200, null=True, verbose_name='Fuente del Canon Fijo'),
        ),
        migrations.AddField(
            model_name='calculofacturacionventas',
            name='fuente_canon_minimo_garantizado',
            field=models.CharField(blank=True, help_text='De dónde se tomó el Canon Mínimo Garantizado vigente (Otro Sí, Cálculo IPC/Salario Mínimo o Contrato base)', max_length=200, null=True, verbose_name='Fuente del Canon Mínimo Garantizado'),
        ),
    ]
