# Generated by Django 5.0.11 on 2026-08-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0078_agregar_fuente_canon_calculo_facturacion_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logos/', verbose_name='Logo de la Empresa'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_contratistas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Contratistas y subcontratistas'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_dano_moral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Daño moral'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_estabilidad_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Estabilidad de la obra'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_gastos_medicos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Gastos médicos'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_lucro_cesante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Lucro cesante'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_patronal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Patronal'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_perjuicios_extrapatrimoniales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Perjuicios extrapatrimoniales'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_plo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='PLO (Predios, Labores y Operaciones)'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='rce_amparo_vehiculos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Vehículos propios y no propios'),
        ),
    ]
