# Generated by Django 5.0.11 on 2026-08-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0078_agregar_fuente_canon_calculo_facturacion_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logos/', verbose_name='Logo de la Empresa'),
        ),
    ]
