from django.urls import path
from . import views

app_name = 'gestion'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('exportaciones/', views.exportaciones, name='exportaciones'),
    path('exportaciones/contratos/', views.exportar_contratos, name='exportar_contratos'),
    path('exportaciones/alertas-vencimiento/', views.exportar_alertas_vencimiento, name='exportar_alertas_vencimiento'),
    path('exportaciones/alertas-polizas/', views.exportar_alertas_polizas, name='exportar_alertas_polizas'),
    path('exportaciones/alertas-preaviso/', views.exportar_alertas_preaviso, name='exportar_alertas_preaviso'),
    path('exportaciones/alertas-ipc/', views.exportar_alertas_ipc, name='exportar_alertas_ipc'),
    path('exportaciones/alertas-salario-minimo/', views.exportar_alertas_salario_minimo, name='exportar_alertas_salario_minimo'),
    path('exportaciones/alertas-polizas-requeridas/', views.exportar_alertas_polizas_requeridas, name='exportar_alertas_polizas_requeridas'),
    path('exportaciones/alertas-terminacion/', views.exportar_alertas_terminacion, name='exportar_alertas_terminacion'),
    path('contratos/', views.lista_contratos, name='lista_contratos'),
    path('contratos/nuevo/', views.nuevo_contrato, name='nuevo_contrato'),
    path('contratos/<int:contrato_id>/', views.detalle_contrato, name='detalle_contrato'),
    path('contratos/<int:contrato_id>/editar/', views.editar_contrato, name='editar_contrato'),
    path('contratos/<int:contrato_id>/eliminar/', views.eliminar_contrato, name='eliminar_contrato'),
    path('terceros/nuevo/', views.nuevo_arrendatario, name='nuevo_arrendatario'),
    path('terceros/', views.lista_arrendatarios, name='lista_arrendatarios'),
    path('terceros/<int:arrendatario_id>/editar/', views.editar_arrendatario, name='editar_arrendatario'),
    path('terceros/<int:arrendatario_id>/eliminar/', views.eliminar_arrendatario, name='eliminar_arrendatario'),
    path('locales/nuevo/', views.nuevo_local, name='nuevo_local'),
    path('locales/', views.lista_locales, name='lista_locales'),
    path('locales/<int:local_id>/editar/', views.editar_local, name='editar_local'),
    path('locales/<int:local_id>/eliminar/', views.eliminar_local, name='eliminar_local'),
    path('tipos-contrato/nuevo/', views.nuevo_tipo_contrato, name='nuevo_tipo_contrato'),
    path('tipos-contrato/', views.lista_tipos_contrato, name='lista_tipos_contrato'),
    path('tipos-contrato/<int:tipo_id>/editar/', views.editar_tipo_contrato, name='editar_tipo_contrato'),
    path('tipos-contrato/<int:tipo_id>/eliminar/', views.eliminar_tipo_contrato, name='eliminar_tipo_contrato'),
    path('tipos-servicio/nuevo/', views.nuevo_tipo_servicio, name='nuevo_tipo_servicio'),
    path('tipos-servicio/', views.lista_tipos_servicio, name='lista_tipos_servicio'),
    path('tipos-servicio/<int:tipo_id>/editar/', views.editar_tipo_servicio, name='editar_tipo_servicio'),
    path('tipos-servicio/<int:tipo_id>/eliminar/', views.eliminar_tipo_servicio, name='eliminar_tipo_servicio'),
    path('contratos/<int:contrato_id>/polizas/', views.gestionar_polizas, name='gestionar_polizas'),
    path('contratos/<int:contrato_id>/polizas/nueva/', views.nueva_poliza, name='nueva_poliza'),
    path('contratos/<int:contrato_id>/polizas/seguimiento/agregar/', views.agregar_seguimiento_poliza, name='agregar_seguimiento_poliza'),
    path('polizas/<int:poliza_id>/editar/', views.editar_poliza, name='editar_poliza'),
    path('polizas/<int:poliza_id>/eliminar/', views.eliminar_poliza, name='eliminar_poliza'),
    path('polizas/<int:poliza_id>/validar/', views.validar_poliza, name='validar_poliza'),
    path('seguimientos-poliza/<int:seguimiento_id>/editar/', views.editar_seguimiento_poliza, name='editar_seguimiento_poliza'),
    path('seguimientos-poliza/<int:seguimiento_id>/eliminar/', views.eliminar_seguimiento_poliza, name='eliminar_seguimiento_poliza'),
    path('configuracion-empresa/', views.configuracion_empresa, name='configuracion_empresa'),
    
    # URLs de Otro Sí
    path('contratos/<int:contrato_id>/otrosi/', views.lista_otrosi, name='lista_otrosi'),
    path('contratos/<int:contrato_id>/otrosi/nuevo/', views.nuevo_otrosi, name='nuevo_otrosi'),
    path('otrosi/<int:otrosi_id>/', views.detalle_otrosi, name='detalle_otrosi'),
    path('otrosi/<int:otrosi_id>/editar/', views.editar_otrosi, name='editar_otrosi'),
    path('otrosi/<int:otrosi_id>/eliminar/', views.eliminar_otrosi, name='eliminar_otrosi'),
    path('otrosi/<int:otrosi_id>/enviar-revision/', views.enviar_a_revision_otrosi, name='enviar_revision_otrosi'),
    path('otrosi/<int:otrosi_id>/aprobar/', views.aprobar_otrosi, name='aprobar_otrosi'),
    path('contratos/<int:contrato_id>/vista-vigente/', views.vista_vigente_contrato, name='vista_vigente_contrato'),
    path('contratos/<int:contrato_id>/seguimiento/agregar/', views.agregar_seguimiento_contrato, name='agregar_seguimiento_contrato'),
    path('seguimientos-contrato/<int:seguimiento_id>/editar/', views.editar_seguimiento_contrato, name='editar_seguimiento_contrato'),
    path('seguimientos-contrato/<int:seguimiento_id>/eliminar/', views.eliminar_seguimiento_contrato, name='eliminar_seguimiento_contrato'),
    path('contratos/<int:contrato_id>/autorizar-renovacion-automatica/', views.autorizar_renovacion_automatica, name='autorizar_renovacion_automatica'),
    path('renovaciones-automaticas/', views.gestion_renovaciones_automaticas, name='gestion_renovaciones_automaticas'),
    path('renovaciones-automaticas/<int:renovacion_id>/editar/', views.editar_renovacion_automatica, name='editar_renovacion_automatica'),
    path('renovaciones-automaticas/<int:renovacion_id>/anular/', views.anular_renovacion_automatica, name='anular_renovacion_automatica'),
    
    # URLs de Informes de Ventas
    path('informes-ventas/', views.lista_informes_ventas, name='lista_informes_ventas'),
    path('informes-ventas/nuevo/', views.nuevo_informe_ventas, name='nuevo_informe_ventas'),
    path('informes-ventas/<int:informe_id>/editar/', views.editar_informe_ventas, name='editar_informe_ventas'),
    path('informes-ventas/<int:informe_id>/marcar-entregado/', views.marcar_entregado_informe, name='marcar_entregado_informe'),
    path('informes-ventas/<int:informe_id>/marcar-pendiente/', views.marcar_pendiente_informe, name='marcar_pendiente_informe'),
    path('informes-ventas/<int:informe_id>/eliminar/', views.eliminar_informe_ventas, name='eliminar_informe_ventas'),
    path('informes-ventas/calcular-facturacion/', views.calcular_facturacion, name='calcular_facturacion'),
    path('informes-ventas/calculo/<int:calculo_id>/resultado/', views.resultado_calculo_facturacion, name='resultado_calculo_facturacion'),
    path('informes-ventas/<int:informe_id>/finalizar/', views.finalizar_informe_ventas, name='finalizar_informe_ventas'),
    path('informes-ventas/entregados/', views.lista_informes_entregados, name='lista_informes_entregados'),
    path('informes-ventas/exportar-excel/', views.exportar_informes_excel, name='exportar_informes_excel'),
    path('informes-ventas/calculo/<int:calculo_id>/pdf/', views.descargar_pdf_calculo, name='descargar_pdf_calculo'),
    path('informes-ventas/calculo/<int:calculo_id>/excel/', views.descargar_excel_calculo, name='descargar_excel_calculo'),
    
    # URLs de IPC
    path('ipc/', views.lista_ipc_historico, name='lista_ipc_historico'),
    path('ipc/historico/', views.historico_ipc_valores, name='historico_ipc_valores'),
    path('ipc/historico/nuevo/', views.nuevo_ipc_historico, name='nuevo_ipc_historico'),
    path('ipc/historico/<int:ipc_id>/editar/', views.editar_ipc_historico, name='editar_ipc_historico'),
    path('ipc/historico/<int:ipc_id>/eliminar/', views.eliminar_ipc_historico, name='eliminar_ipc_historico'),
    path('ipc/calcular/', views.calcular_ipc, name='calcular_ipc'),
    path('ipc/calcular/confirmar/', views.confirmar_calculo_ipc, name='confirmar_calculo_ipc'),
    path('ipc/calculo/<int:calculo_id>/', views.detalle_calculo_ipc, name='detalle_calculo_ipc'),
    path('ipc/calculo/<int:calculo_id>/editar/', views.editar_calculo_ipc, name='editar_calculo_ipc'),
    path('ipc/calculo/<int:calculo_id>/eliminar/', views.eliminar_calculo_ipc, name='eliminar_calculo_ipc'),
    path('ipc/calculos/', views.lista_calculos_ipc, name='lista_calculos_ipc'),
    path('ipc/contratos-pendientes/', views.contratos_pendientes_ipc, name='contratos_pendientes_ipc'),
    path('ipc/ajax/obtener-canon-anterior/', views.obtener_canon_anterior_ajax, name='obtener_canon_anterior_ajax'),
    # URLs de Configuración IPC
    path('ipc/configuracion/tipos/', views.lista_tipos_condicion_ipc, name='lista_tipos_condicion_ipc'),
    path('ipc/configuracion/tipos/nuevo/', views.nuevo_tipo_condicion_ipc, name='nuevo_tipo_condicion_ipc'),
    path('ipc/configuracion/tipos/<int:tipo_id>/editar/', views.editar_tipo_condicion_ipc, name='editar_tipo_condicion_ipc'),
    path('ipc/configuracion/tipos/<int:tipo_id>/eliminar/', views.eliminar_tipo_condicion_ipc, name='eliminar_tipo_condicion_ipc'),
    path('ipc/configuracion/periodicidades/', views.lista_periodicidades_ipc, name='lista_periodicidades_ipc'),
    path('ipc/configuracion/periodicidades/nueva/', views.nueva_periodicidad_ipc, name='nueva_periodicidad_ipc'),
    path('ipc/configuracion/periodicidades/<int:periodicidad_id>/editar/', views.editar_periodicidad_ipc, name='editar_periodicidad_ipc'),
    path('ipc/configuracion/periodicidades/<int:periodicidad_id>/eliminar/', views.eliminar_periodicidad_ipc, name='eliminar_periodicidad_ipc'),
    
    # URLs de Salario Mínimo
    path('salario-minimo/', views.lista_salario_minimo_historico, name='lista_salario_minimo_historico'),
    path('salario-minimo/historico/', views.historico_salario_minimo_valores, name='historico_salario_minimo_valores'),
    path('salario-minimo/historico/nuevo/', views.nuevo_salario_minimo_historico, name='nuevo_salario_minimo_historico'),
    path('salario-minimo/historico/<int:smlv_id>/editar/', views.editar_salario_minimo_historico, name='editar_salario_minimo_historico'),
    path('salario-minimo/historico/<int:smlv_id>/eliminar/', views.eliminar_salario_minimo_historico, name='eliminar_salario_minimo_historico'),
    path('salario-minimo/calcular/', views.calcular_salario_minimo, name='calcular_salario_minimo'),
    path('salario-minimo/calcular/confirmar/', views.confirmar_calculo_salario_minimo, name='confirmar_calculo_salario_minimo'),
    path('salario-minimo/calculo/<int:calculo_id>/', views.detalle_calculo_salario_minimo, name='detalle_calculo_salario_minimo'),
    path('salario-minimo/calculo/<int:calculo_id>/editar/', views.editar_calculo_salario_minimo, name='editar_calculo_salario_minimo'),
    path('salario-minimo/calculo/<int:calculo_id>/eliminar/', views.eliminar_calculo_salario_minimo, name='eliminar_calculo_salario_minimo'),
    path('salario-minimo/calculos/', views.lista_calculos_salario_minimo, name='lista_calculos_salario_minimo'),
    path('salario-minimo/contratos-pendientes/', views.contratos_pendientes_salario_minimo, name='contratos_pendientes_salario_minimo'),
    path('salario-minimo/ajax/obtener-canon-anterior/', views.obtener_canon_anterior_salario_minimo_ajax, name='obtener_canon_anterior_salario_minimo_ajax'),
    path('salario-minimo/ajax/obtener-variacion/', views.obtener_variacion_salario_minimo_ajax, name='obtener_variacion_salario_minimo_ajax'),
    
    # URLs de Cláusulas
    path('clausulas/parametrizar/', views.parametrizar_clausulas, name='parametrizar_clausulas'),
    path('clausulas/parametrizar/guardar/', views.guardar_parametrizacion_clausulas, name='guardar_parametrizacion_clausulas'),
    path('clausulas/gestionar/', views.gestionar_clausulas, name='gestionar_clausulas'),
    path('clausulas/crear/', views.crear_clausula, name='crear_clausula'),
    path('clausulas/<int:clausula_id>/editar/', views.editar_clausula, name='editar_clausula'),
    path('clausulas/<int:clausula_id>/eliminar/', views.eliminar_clausula, name='eliminar_clausula'),
    path('contratos/<int:contrato_id>/auditoria-clausulas/', views.auditoria_clausulas_contrato, name='auditoria_clausulas_contrato'),
    path('contratos/<int:contrato_id>/guardar-clausulas/', views.guardar_clausulas_contrato, name='guardar_clausulas_contrato'),
    
]